"""ledg

Revision ID: 0fe7fca80138
Revises: 329dcd27a1c7
Create Date: 2026-05-23 21:36:32.096291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe7fca80138'
down_revision: Union[str, Sequence[str], None] = '329dcd27a1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chart_of_accounts_organisation_id'), table_name='chart_of_accounts')
    op.drop_constraint(op.f('chart_of_accounts_organisation_id_fkey'), 'chart_of_accounts', type_='foreignkey')
    op.drop_column('chart_of_accounts', 'organisation_id')
    op.drop_index(op.f('ix_journal_entries_organisation_id'), table_name='journal_entries')
    op.drop_constraint(op.f('journal_entries_organisation_id_fkey'), 'journal_entries', type_='foreignkey')
    op.drop_column('journal_entries', 'organisation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('journal_entries_organisation_id_fkey'), 'journal_entries', 'organisations', ['organisation_id'], ['id'])
    op.create_index(op.f('ix_journal_entries_organisation_id'), 'journal_entries', ['organisation_id'], unique=False)
    op.add_column('chart_of_accounts', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('chart_of_accounts_organisation_id_fkey'), 'chart_of_accounts', 'organisations', ['organisation_id'], ['id'])
    op.create_index(op.f('ix_chart_of_accounts_organisation_id'), 'chart_of_accounts', ['organisation_id'], unique=False)
    # ### end Alembic commands ###
