"""saving_user

Revision ID: 11a074a938cb
Revises: 7c677217b709
Create Date: 2026-05-24 22:19:39.065092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a074a938cb'
down_revision: Union[str, Sequence[str], None] = '7c677217b709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_money_transactions',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('provider_response', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobile_money_transactions_id'), 'mobile_money_transactions', ['id'], unique=False)
    op.add_column('loan_products', sa.Column('loan_receivable_account_id', sa.UUID(), nullable=True))
    op.add_column('loan_products', sa.Column('interest_income_account_id', sa.UUID(), nullable=True))
    op.add_column('loan_products', sa.Column('penalty_income_account_id', sa.UUID(), nullable=True))
    op.add_column('loan_products', sa.Column('processing_fee_account_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'loan_products', 'chart_of_accounts', ['penalty_income_account_id'], ['id'])
    op.create_foreign_key(None, 'loan_products', 'chart_of_accounts', ['processing_fee_account_id'], ['id'])
    op.create_foreign_key(None, 'loan_products', 'chart_of_accounts', ['interest_income_account_id'], ['id'])
    op.create_foreign_key(None, 'loan_products', 'chart_of_accounts', ['loan_receivable_account_id'], ['id'])
    op.add_column('share_products', sa.Column('share_capital_account_id', sa.UUID(), nullable=True))
    op.add_column('share_products', sa.Column('dividend_expense_account_id', sa.UUID(), nullable=True))
    op.add_column('share_products', sa.Column('dividend_payable_account_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'share_products', 'chart_of_accounts', ['share_capital_account_id'], ['id'])
    op.create_foreign_key(None, 'share_products', 'chart_of_accounts', ['dividend_payable_account_id'], ['id'])
    op.create_foreign_key(None, 'share_products', 'chart_of_accounts', ['dividend_expense_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'share_products', type_='foreignkey')
    op.drop_constraint(None, 'share_products', type_='foreignkey')
    op.drop_constraint(None, 'share_products', type_='foreignkey')
    op.drop_column('share_products', 'dividend_payable_account_id')
    op.drop_column('share_products', 'dividend_expense_account_id')
    op.drop_column('share_products', 'share_capital_account_id')
    op.drop_constraint(None, 'loan_products', type_='foreignkey')
    op.drop_constraint(None, 'loan_products', type_='foreignkey')
    op.drop_constraint(None, 'loan_products', type_='foreignkey')
    op.drop_constraint(None, 'loan_products', type_='foreignkey')
    op.drop_column('loan_products', 'processing_fee_account_id')
    op.drop_column('loan_products', 'penalty_income_account_id')
    op.drop_column('loan_products', 'interest_income_account_id')
    op.drop_column('loan_products', 'loan_receivable_account_id')
    op.drop_index(op.f('ix_mobile_money_transactions_id'), table_name='mobile_money_transactions')
    op.drop_table('mobile_money_transactions')
    # ### end Alembic commands ###
