"""ledger

Revision ID: 329dcd27a1c7
Revises: 3c592faceda7
Create Date: 2026-05-23 19:05:59.397919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329dcd27a1c7'
down_revision: Union[str, Sequence[str], None] = '3c592faceda7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_organisation_id'), table_name='ledger_entries')
    op.drop_constraint(op.f('ledger_entries_organisation_id_fkey'), 'ledger_entries', type_='foreignkey')
    op.drop_column('ledger_entries', 'organisation_id')
    op.drop_index(op.f('ix_ledger_lines_organisation_id'), table_name='ledger_lines')
    op.drop_constraint(op.f('ledger_lines_organisation_id_fkey'), 'ledger_lines', type_='foreignkey')
    op.drop_column('ledger_lines', 'organisation_id')
    op.alter_column('savings_transactions', 'tx_type_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_savings_transactions_tx_type_id'), table_name='savings_transactions')
    op.drop_constraint(op.f('savings_transactions_processed_by_id_fkey'), 'savings_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'savings_transactions', 'members', ['processed_by_id'], ['id'])
    op.drop_column('savings_transactions', 'tx_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings_transactions', sa.Column('tx_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'savings_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('savings_transactions_processed_by_id_fkey'), 'savings_transactions', 'users', ['processed_by_id'], ['id'])
    op.create_index(op.f('ix_savings_transactions_tx_type_id'), 'savings_transactions', ['tx_type_id'], unique=False)
    op.alter_column('savings_transactions', 'tx_type_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('ledger_lines', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('ledger_lines_organisation_id_fkey'), 'ledger_lines', 'organisations', ['organisation_id'], ['id'])
    op.create_index(op.f('ix_ledger_lines_organisation_id'), 'ledger_lines', ['organisation_id'], unique=False)
    op.add_column('ledger_entries', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('ledger_entries_organisation_id_fkey'), 'ledger_entries', 'organisations', ['organisation_id'], ['id'])
    op.create_index(op.f('ix_ledger_entries_organisation_id'), 'ledger_entries', ['organisation_id'], unique=False)
    # ### end Alembic commands ###
