"""users table update

Revision ID: 3327a63dc30b
Revises: e5c1007aca25
Create Date: 2026-05-23 14:26:26.704367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3327a63dc30b'
down_revision: Union[str, Sequence[str], None] = 'e5c1007aca25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_name', sa.String(length=15), nullable=True))
    op.create_unique_constraint(None, 'users', ['role_name'])
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_name'], ['role'], ondelete='RESTRICT')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'role_name')
    # ### end Alembic commands ###
