"""users table upd

Revision ID: 3c592faceda7
Revises: dfdde74f2b1f
Create Date: 2026-05-23 15:46:47.806879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c592faceda7'
down_revision: Union[str, Sequence[str], None] = 'dfdde74f2b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_logs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('login_logs_member_id_fkey'), 'login_logs', type_='foreignkey')
    op.create_foreign_key(None, 'login_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('login_logs', 'member_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_logs', sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'login_logs', type_='foreignkey')
    op.create_foreign_key(op.f('login_logs_member_id_fkey'), 'login_logs', 'users', ['member_id'], ['id'], ondelete='CASCADE')
    op.drop_column('login_logs', 'user_id')
    # ### end Alembic commands ###
