"""status

Revision ID: 43d2f731b5ac
Revises: ba7aea65df78
Create Date: 2026-05-18 15:52:46.504700

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "43d2f731b5ac"
down_revision: Union[str, Sequence[str], None] = "ba7aea65df78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "marital_statuses", sa.Column("description", sa.Text(), nullable=True)
    )
    op.alter_column(
        "marital_statuses",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_marital_statuses_id"), "marital_statuses", ["id"], unique=False
    )
    op.create_unique_constraint(None, "marital_statuses", ["status"])
    op.add_column("members", sa.Column("organisation_id", sa.UUID(), nullable=False))
    op.add_column("members", sa.Column("physical_address", sa.Text(), nullable=True))
    op.alter_column(
        "members",
        "country",
        existing_type=sa.TEXT(),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "members",
        "joined_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.Date(),
        existing_nullable=True,
    )
    op.alter_column(
        "members",
        "exit_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.Date(),
        existing_nullable=True,
    )
    op.drop_constraint(op.f("members_phone_key"), "members", type_="unique")
    op.drop_constraint(op.f("members_phone_secondary_key"), "members", type_="unique")
    op.drop_constraint(op.f("uq_member_no_per_org"), "members", type_="unique")
    op.create_unique_constraint(
        "uq_member_no_per_org", "members", ["organisation_id", "member_no"]
    )
    op.create_index(
        op.f("ix_members_organisation_id"), "members", ["organisation_id"], unique=False
    )
    op.drop_constraint(op.f("members_user_id_fkey"), "members", type_="foreignkey")
    op.drop_constraint(
        op.f("members_marital_status_fkey"), "members", type_="foreignkey"
    )
    op.create_foreign_key(None, "members", "organisations", ["organisation_id"], ["id"])
    op.create_foreign_key(
        None, "members", "marital_statuses", ["marital_status_id"], ["id"]
    )
    op.drop_column("members", "phone")
    op.drop_column("members", "user_id")
    op.add_column(
        "next_of_kin",
        sa.Column("relationship_to_member", sa.String(length=100), nullable=True),
    )
    op.alter_column(
        "next_of_kin", "marital_status_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "next_of_kin", "email", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_constraint(op.f("next_of_kin_phone_key"), "next_of_kin", type_="unique")
    op.drop_constraint(
        op.f("next_of_kin_marital_status_fkey"), "next_of_kin", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "next_of_kin", "marital_statuses", ["marital_status_id"], ["id"]
    )
    op.drop_column("next_of_kin", "middle_name")
    op.drop_column("next_of_kin", "member_relationship")
    user_type_enum = postgresql.ENUM("MEMBER", "STAFF", name="usertypeenum")
    user_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column("users", sa.Column("organisation_id", sa.UUID(), nullable=False))
    op.add_column(
        "users",
        sa.Column(
            "user_type", sa.Enum("MEMBER", "STAFF", name="usertypeenum"), nullable=False
        ),
    )
    op.add_column("users", sa.Column("member_id", sa.UUID(), nullable=True))
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "users",
        "last_login",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        postgresql_using="last_login::timestamp with time zone",
    )
    op.drop_constraint(op.f("users_phone_key"), "users", type_="unique")
    op.drop_constraint(op.f("uq_user_email_per_org"), "users", type_="unique")
    op.create_unique_constraint(
        "uq_user_email_per_org", "users", ["organisation_id", "email"]
    )
    op.create_index(
        op.f("ix_users_organisation_id"), "users", ["organisation_id"], unique=False
    )
    op.create_unique_constraint(None, "users", ["member_id"])
    op.drop_constraint(op.f("users_role_id_fkey"), "users", type_="foreignkey")
    op.create_foreign_key(None, "users", "organisations", ["organisation_id"], ["id"])
    op.create_foreign_key(
        None, "users", "members", ["member_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "users", "roles", ["role_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_column("users", "middle_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "middle_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("users_role_id_fkey"),
        "users",
        "roles",
        ["role_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_index(op.f("ix_users_organisation_id"), table_name="users")
    op.drop_constraint("uq_user_email_per_org", "users", type_="unique")
    op.create_unique_constraint(
        op.f("uq_user_email_per_org"),
        "users",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("users_phone_key"), "users", ["phone"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "users",
        "last_login",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_column("users", "member_id")
    op.drop_column("users", "user_type")
    op.drop_column("users", "organisation_id")
    user_type_enum = postgresql.ENUM("MEMBER", "STAFF", name="usertypeenum")
    user_type_enum.drop(op.get_bind(), checkfirst=True)
    op.add_column(
        "next_of_kin",
        sa.Column(
            "member_relationship",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "next_of_kin",
        sa.Column(
            "middle_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "next_of_kin", type_="foreignkey")
    op.create_foreign_key(
        op.f("next_of_kin_marital_status_fkey"),
        "next_of_kin",
        "marital_statuses",
        ["marital_status_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        op.f("next_of_kin_phone_key"),
        "next_of_kin",
        ["phone"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "next_of_kin", "email", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "next_of_kin", "marital_status_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("next_of_kin", "relationship_to_member")
    op.add_column(
        "members", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "members",
        sa.Column("phone", sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "members", type_="foreignkey")
    op.drop_constraint(None, "members", type_="foreignkey")
    op.create_foreign_key(
        op.f("members_marital_status_fkey"),
        "members",
        "marital_statuses",
        ["marital_status_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("members_user_id_fkey"),
        "members",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_members_organisation_id"), table_name="members")
    op.drop_constraint("uq_member_no_per_org", "members", type_="unique")
    op.create_unique_constraint(
        op.f("uq_member_no_per_org"),
        "members",
        ["member_no"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("members_phone_secondary_key"),
        "members",
        ["phone_secondary"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("members_phone_key"),
        "members",
        ["phone"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "members",
        "exit_date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "members",
        "joined_date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "members",
        "country",
        existing_type=sa.String(length=100),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("members", "physical_address")
    op.drop_column("members", "organisation_id")
    op.drop_constraint(None, "marital_statuses", type_="unique")
    op.drop_index(op.f("ix_marital_statuses_id"), table_name="marital_statuses")
    op.alter_column(
        "marital_statuses",
        "status",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.drop_column("marital_statuses", "description")
    # ### end Alembic commands ###
