"""chang

Revision ID: 4e0c3e95b362
Revises: 2857ab8e0145
Create Date: 2026-05-18 09:15:26.968241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e0c3e95b362'
down_revision: Union[str, Sequence[str], None] = '2857ab8e0145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_genders_id'), 'genders', ['id'], unique=False)
    op.create_index(op.f('ix_member_statuses_id'), 'member_statuses', ['id'], unique=False)
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_index(op.f('ix_next_of_kin_id'), 'next_of_kin', ['id'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.drop_constraint(op.f('share_transactions_counterpart_account_id_fkey'), 'share_transactions', type_='foreignkey')
    op.drop_column('share_transactions', 'counterpart_account_id')
    op.create_index(op.f('ix_user_types_id'), 'user_types', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_user_types_id'), table_name='user_types')
    op.add_column('share_transactions', sa.Column('counterpart_account_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('share_transactions_counterpart_account_id_fkey'), 'share_transactions', 'share_accounts', ['counterpart_account_id'], ['id'])
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_next_of_kin_id'), table_name='next_of_kin')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_index(op.f('ix_member_statuses_id'), table_name='member_statuses')
    op.drop_index(op.f('ix_genders_id'), table_name='genders')
    # ### end Alembic commands ###
