"""create_new_tables

Revision ID: 579971398759
Revises: 23744f8c4ddd
Create Date: 2026-05-14 18:49:17.331855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579971398759'
down_revision: Union[str, Sequence[str], None] = '23744f8c4ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('address_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nationality', sa.String(length=30), nullable=False),
    sa.Column('district', sa.String(length=40), nullable=False),
    sa.Column('sub_county', sa.String(length=50), nullable=False),
    sa.Column('parish', sa.String(length=50), nullable=False),
    sa.Column('village', sa.String(length=50), nullable=False),
    sa.Column('postal_code', sa.String(length=50), nullable=True),
    sa.Column('address_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('address_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('profile',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.String(length=15), nullable=False),
    sa.Column('id_number', sa.String(length=20), nullable=True),
    sa.Column('occupation', sa.String(length=50), nullable=False),
    sa.Column('monthly_income', sa.String(length=50), nullable=False),
    sa.Column('marital_status', sa.String(length=50), nullable=False),
    sa.Column('employer_name', sa.String(length=50), nullable=True),
    sa.Column('primary_language', sa.String(length=50), nullable=False),
    sa.Column('user_avatar', sa.TEXT(), nullable=True),
    sa.Column('profile_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('profile_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('id_number'),
    sa.UniqueConstraint('member_id'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('user_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('user_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('user_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'profile_avatr')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_avatr', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'user_updated_at')
    op.drop_column('users', 'user_created_at')
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'username')
    op.drop_table('profile')
    op.drop_table('address')
    # ### end Alembic commands ###
