"""changes

Revision ID: 5c99d740f48b
Revises: 8a1021d710fb
Create Date: 2026-05-17 19:48:23.877068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c99d740f48b'
down_revision: Union[str, Sequence[str], None] = '8a1021d710fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('member_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('members', sa.Column('gender_id', sa.UUID(), nullable=False))
    op.add_column('members', sa.Column('status_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.create_foreign_key(None, 'members', 'genders', ['gender_id'], ['id'])
    op.create_foreign_key(None, 'members', 'member_statuses', ['status_id'], ['id'])
    op.drop_column('members', 'gender')
    op.drop_column('members', 'status')
    op.drop_index(op.f('ix_next_of_kin_id'), table_name='next_of_kin')
    op.add_column('users', sa.Column('role_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('MEMBER', 'LOAN_OFFICER', 'TREASURER', 'BRANCH_MANAGER', 'ADMIN', 'SUPER_ADMIN', name='roleenum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'role_id')
    op.create_index(op.f('ix_next_of_kin_id'), 'next_of_kin', ['id'], unique=False)
    op.add_column('members', sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'DORMANT', 'SUSPENDED', 'EXITED', name='memberstatusenum'), autoincrement=False, nullable=False))
    op.add_column('members', sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'OTHER', 'UNSPECIFIED', name='genderenum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.drop_column('members', 'status_id')
    op.drop_column('members', 'gender_id')
    op.drop_table('roles')
    op.drop_table('member_statuses')
    op.drop_table('genders')
    # ### end Alembic commands ###
