"""change

Revision ID: 602b96c852c8
Revises: befb6368a209
Create Date: 2026-05-15 14:06:45.260010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602b96c852c8'
down_revision: Union[str, Sequence[str], None] = 'befb6368a209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_logs', sa.Column('attempts', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_logs', 'attempts')
    # ### end Alembic commands ###
