"""new models

Revision ID: 602c1fbbe48b
Revises: 
Create Date: 2026-05-17 18:16:58.674126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602c1fbbe48b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.UUID(), nullable=False),
    sa.Column('account_status', sa.String(length=50), nullable=True),
    sa.Column('account_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('account_name')
    )
    op.create_table('organisations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('registration_no', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('default_currency', sa.String(length=10), nullable=False),
    sa.Column('min_share_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('loan_interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('savings_interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('short_code')
    )
    op.create_index(op.f('ix_organisations_id'), 'organisations', ['id'], unique=False)
    op.create_table('branches',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('manager_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_index(op.f('ix_branches_organisation_id'), 'branches', ['organisation_id'], unique=False)
    op.create_table('chart_of_accounts',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE', name='accounttypeenum'), nullable=False),
    sa.Column('account_category', sa.Enum('CASH', 'BANK', 'MOBILE_MONEY', 'LOANS_RECEIVABLE', 'INTEREST_RECEIVABLE', 'MEMBER_SAVINGS', 'MEMBER_SHARES', 'DIVIDENDS_PAYABLE', 'RETAINED_EARNINGS', 'RESERVE_FUND', 'INTEREST_INCOME', 'FEE_INCOME', 'PENALTY_INCOME', 'OPERATING_EXPENSE', 'INTEREST_EXPENSE', 'LOAN_LOSS_PROVISION', name='accountcategoryenum'), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['chart_of_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_of_accounts_id'), 'chart_of_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_chart_of_accounts_organisation_id'), 'chart_of_accounts', ['organisation_id'], unique=False)
    op.create_table('loan_products',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('interest_rate_pa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('interest_method', sa.Enum('FLAT_RATE', 'REDUCING_BALANCE', name='interestmethodenum'), nullable=False),
    sa.Column('repayment_frequency', sa.Enum('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY', 'LUMP_SUM', name='repaymentfrequencyenum'), nullable=False),
    sa.Column('min_term_months', sa.Integer(), nullable=False),
    sa.Column('max_term_months', sa.Integer(), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('loan_to_savings_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('loan_to_shares_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('requires_guarantor', sa.Boolean(), nullable=False),
    sa.Column('min_guarantors', sa.Integer(), nullable=False),
    sa.Column('requires_collateral', sa.Boolean(), nullable=False),
    sa.Column('penalty_rate_per_day', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('processing_fee_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_products_id'), 'loan_products', ['id'], unique=False)
    op.create_index(op.f('ix_loan_products_organisation_id'), 'loan_products', ['organisation_id'], unique=False)
    op.create_table('savings_products',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('product_type', sa.Enum('ORDINARY', 'FIXED_DEPOSIT', 'GOAL', 'EMERGENCY', 'CHRISTMAS', name='savingsproducttypeenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('interest_rate_pa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_opening_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('min_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('max_balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('withdrawal_allowed', sa.Boolean(), nullable=False),
    sa.Column('lock_period_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_products_id'), 'savings_products', ['id'], unique=False)
    op.create_index(op.f('ix_savings_products_organisation_id'), 'savings_products', ['organisation_id'], unique=False)
    op.create_table('share_products',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('product_type', sa.Enum('ORDINARY', 'PREFERENCE', 'BONUS', name='shareproducttypeenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nominal_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('min_shares', sa.Integer(), nullable=False),
    sa.Column('max_shares', sa.Integer(), nullable=True),
    sa.Column('is_transferable', sa.Boolean(), nullable=False),
    sa.Column('is_redeemable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_products_id'), 'share_products', ['id'], unique=False)
    op.create_index(op.f('ix_share_products_organisation_id'), 'share_products', ['organisation_id'], unique=False)
    op.create_table('members',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('member_no', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'UNSPECIFIED', name='genderenum'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('phone_primary', sa.String(length=30), nullable=True),
    sa.Column('phone_secondary', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('physical_address', sa.Text(), nullable=True),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'DORMANT', 'SUSPENDED', 'EXITED', name='memberstatusenum'), nullable=False),
    sa.Column('joined_date', sa.Date(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'member_no', name='uq_member_no_per_org')
    )
    op.create_index(op.f('ix_members_branch_id'), 'members', ['branch_id'], unique=False)
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_index(op.f('ix_members_organisation_id'), 'members', ['organisation_id'], unique=False)
    op.create_table('next_of_kin',
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('national_id', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_next_of_kin_id'), 'next_of_kin', ['id'], unique=False)
    op.create_index(op.f('ix_next_of_kin_member_id'), 'next_of_kin', ['member_id'], unique=False)
    op.create_table('savings_accounts',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('account_no', sa.String(length=50), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DORMANT', 'FROZEN', 'CLOSED', name='savingsaccountstatusenum'), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['savings_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_accounts_branch_id'), 'savings_accounts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_savings_accounts_id'), 'savings_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_savings_accounts_member_id'), 'savings_accounts', ['member_id'], unique=False)
    op.create_index(op.f('ix_savings_accounts_organisation_id'), 'savings_accounts', ['organisation_id'], unique=False)
    op.create_table('share_accounts',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('account_no', sa.String(length=50), nullable=False),
    sa.Column('shares_held', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['share_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_accounts_branch_id'), 'share_accounts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_share_accounts_id'), 'share_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_share_accounts_member_id'), 'share_accounts', ['member_id'], unique=False)
    op.create_index(op.f('ix_share_accounts_organisation_id'), 'share_accounts', ['organisation_id'], unique=False)
    op.create_table('users',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('MEMBER', 'LOAN_OFFICER', 'TREASURER', 'BRANCH_MANAGER', 'ADMIN', 'SUPER_ADMIN', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id'),
    sa.UniqueConstraint('organisation_id', 'email', name='uq_user_email_per_org')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_organisation_id'), 'users', ['organisation_id'], unique=False)
    op.create_table('address',
    sa.Column('address_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('nationality', sa.String(length=30), nullable=False),
    sa.Column('district', sa.String(length=40), nullable=False),
    sa.Column('sub_county', sa.String(length=50), nullable=False),
    sa.Column('parish', sa.String(length=50), nullable=False),
    sa.Column('village', sa.String(length=50), nullable=False),
    sa.Column('postal_code', sa.String(length=50), nullable=True),
    sa.Column('address_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('address_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['users.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address_id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_table('dividends',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('period_label', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'PAID', 'REVERSED', name='dividendstatusenum'), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['share_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividends_id'), 'dividends', ['id'], unique=False)
    op.create_index(op.f('ix_dividends_organisation_id'), 'dividends', ['organisation_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('entry_no', sa.String(length=50), nullable=False),
    sa.Column('entry_type', sa.Enum('SAVINGS_DEPOSIT', 'SAVINGS_WITHDRAWAL', 'SAVINGS_INTEREST', 'SHARE_PURCHASE', 'SHARE_REDEMPTION', 'DIVIDEND_PAYMENT', 'LOAN_DISBURSEMENT', 'LOAN_REPAYMENT', 'LOAN_PENALTY', 'FEE_CHARGE', 'JOURNAL', 'TRANSFER', name='ledgerentrytypeenum'), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('total_debit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_credit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'POSTED', 'REVERSED', 'VOIDED', name='ledgerentrystatusenum'), nullable=False),
    sa.Column('reversal_of_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('total_debit = total_credit', name='ck_ledger_balanced'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['ledger_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_branch_id'), 'ledger_entries', ['branch_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_id'), 'ledger_entries', ['id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_organisation_id'), 'ledger_entries', ['organisation_id'], unique=False)
    op.create_table('loan_applications',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('application_no', sa.String(length=50), nullable=False),
    sa.Column('applied_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='loanapplicationstatusenum'), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=False),
    sa.Column('reviewed_date', sa.Date(), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('decision_by_id', sa.UUID(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['decision_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['loan_products.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_applications_branch_id'), 'loan_applications', ['branch_id'], unique=False)
    op.create_index(op.f('ix_loan_applications_id'), 'loan_applications', ['id'], unique=False)
    op.create_index(op.f('ix_loan_applications_member_id'), 'loan_applications', ['member_id'], unique=False)
    op.create_index(op.f('ix_loan_applications_organisation_id'), 'loan_applications', ['organisation_id'], unique=False)
    op.create_table('login_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=30), nullable=True),
    sa.Column('user_agent', sa.String(length=250), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('failure_reason', sa.String(length=30), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='1', nullable=False),
    sa.Column('session_id', sa.String(length=30), nullable=True),
    sa.Column('location_country', sa.String(length=50), nullable=True),
    sa.Column('location_city', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['users.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('profile',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.String(length=15), nullable=False),
    sa.Column('id_number', sa.String(length=20), nullable=True),
    sa.Column('occupation', sa.String(length=50), nullable=False),
    sa.Column('monthly_income', sa.String(length=50), nullable=False),
    sa.Column('marital_status', sa.String(length=50), nullable=False),
    sa.Column('employer_name', sa.String(length=50), nullable=True),
    sa.Column('primary_language', sa.String(length=50), nullable=False),
    sa.Column('user_avatar', sa.TEXT(), nullable=True),
    sa.Column('profile_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('profile_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['users.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('id_number'),
    sa.UniqueConstraint('member_id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('transactions',
    sa.Column('txn_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['users.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('txn_id')
    )
    op.create_table('user_accounts',
    sa.Column('user_account_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('user_account_created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_account_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['users.member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_account_id')
    )
    op.create_table('dividend_payments',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('dividend_id', sa.UUID(), nullable=False),
    sa.Column('share_account_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('shares_at_record', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('ledger_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dividend_id'], ['dividends.id'], ),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['share_account_id'], ['share_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividend_payments_dividend_id'), 'dividend_payments', ['dividend_id'], unique=False)
    op.create_index(op.f('ix_dividend_payments_id'), 'dividend_payments', ['id'], unique=False)
    op.create_index(op.f('ix_dividend_payments_organisation_id'), 'dividend_payments', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_dividend_payments_share_account_id'), 'dividend_payments', ['share_account_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('ledger_entry_id', sa.UUID(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=False),
    sa.Column('prepared_by_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['prepared_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ledger_entry_id')
    )
    op.create_index(op.f('ix_journal_entries_branch_id'), 'journal_entries', ['branch_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_journal_entries_organisation_id'), 'journal_entries', ['organisation_id'], unique=False)
    op.create_table('ledger_lines',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('dr_cr', sa.Enum('DEBIT', 'CREDIT', name='drcrenum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_ledger_line_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['chart_of_accounts.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_lines_account_id'), 'ledger_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_ledger_lines_entry_id'), 'ledger_lines', ['entry_id'], unique=False)
    op.create_index(op.f('ix_ledger_lines_id'), 'ledger_lines', ['id'], unique=False)
    op.create_index(op.f('ix_ledger_lines_organisation_id'), 'ledger_lines', ['organisation_id'], unique=False)
    op.create_table('loan_collaterals',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('collateral_type', sa.Enum('LAND', 'VEHICLE', 'BUILDING', 'EQUIPMENT', 'SAVINGS', 'SHARES', 'OTHER', name='collateraltypeenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('document_ref', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_collaterals_application_id'), 'loan_collaterals', ['application_id'], unique=False)
    op.create_index(op.f('ix_loan_collaterals_id'), 'loan_collaterals', ['id'], unique=False)
    op.create_index(op.f('ix_loan_collaterals_organisation_id'), 'loan_collaterals', ['organisation_id'], unique=False)
    op.create_table('loan_guarantors',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('guarantor_id', sa.UUID(), nullable=False),
    sa.Column('guaranteed_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('has_consented', sa.Boolean(), nullable=False),
    sa.Column('consent_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['guarantor_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_guarantors_application_id'), 'loan_guarantors', ['application_id'], unique=False)
    op.create_index(op.f('ix_loan_guarantors_id'), 'loan_guarantors', ['id'], unique=False)
    op.create_index(op.f('ix_loan_guarantors_organisation_id'), 'loan_guarantors', ['organisation_id'], unique=False)
    op.create_table('loans',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('loan_no', sa.String(length=50), nullable=False),
    sa.Column('principal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('interest_rate_pa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('interest_method', sa.Enum('FLAT_RATE', 'REDUCING_BALANCE', name='interestmethodenum'), nullable=False),
    sa.Column('repayment_frequency', sa.Enum('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUALLY', 'LUMP_SUM', name='repaymentfrequencyenum'), nullable=False),
    sa.Column('processing_fee', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_interest', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_payable', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('outstanding_principal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('outstanding_interest', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('outstanding_penalty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('disbursement_date', sa.Date(), nullable=False),
    sa.Column('first_payment_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'IN_ARREARS', 'WRITTEN_OFF', 'CLOSED', name='loanstatusenum'), nullable=False),
    sa.Column('disbursed_by_id', sa.UUID(), nullable=True),
    sa.Column('ledger_entry_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['disbursed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['loan_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index(op.f('ix_loans_branch_id'), 'loans', ['branch_id'], unique=False)
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_index(op.f('ix_loans_member_id'), 'loans', ['member_id'], unique=False)
    op.create_index(op.f('ix_loans_organisation_id'), 'loans', ['organisation_id'], unique=False)
    op.create_table('savings_transactions',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('ledger_entry_id', sa.UUID(), nullable=True),
    sa.Column('tx_type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'INTEREST', 'CHARGE', 'TRANSFER', name='savingstxtypeenum'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('processed_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['savings_accounts.id'], ),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_transactions_account_id'), 'savings_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_savings_transactions_id'), 'savings_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_savings_transactions_organisation_id'), 'savings_transactions', ['organisation_id'], unique=False)
    op.create_table('share_transactions',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('ledger_entry_id', sa.UUID(), nullable=True),
    sa.Column('tx_type', sa.Enum('PURCHASE', 'TRANSFER', 'REDEMPTION', 'BONUS', 'CORRECTION', name='sharetxtypeenum'), nullable=False),
    sa.Column('shares', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('price_per_share', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('shares_after', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('counterpart_account_id', sa.UUID(), nullable=True),
    sa.Column('processed_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['share_accounts.id'], ),
    sa.ForeignKeyConstraint(['counterpart_account_id'], ['share_accounts.id'], ),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_transactions_account_id'), 'share_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_share_transactions_id'), 'share_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_share_transactions_organisation_id'), 'share_transactions', ['organisation_id'], unique=False)
    op.create_table('loan_penalties',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('penalty_type', sa.Enum('LATE_PAYMENT', 'MISSED_PAYMENT', 'EARLY_CLOSURE', name='penaltytypeenum'), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_waived', sa.Boolean(), nullable=False),
    sa.Column('waived_by_id', sa.UUID(), nullable=True),
    sa.Column('raised_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['waived_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_penalties_id'), 'loan_penalties', ['id'], unique=False)
    op.create_index(op.f('ix_loan_penalties_loan_id'), 'loan_penalties', ['loan_id'], unique=False)
    op.create_index(op.f('ix_loan_penalties_organisation_id'), 'loan_penalties', ['organisation_id'], unique=False)
    op.create_table('loan_repayment_schedules',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('instalment_no', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal_due', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('interest_due', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_due', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('principal_paid', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('interest_paid', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('penalty_paid', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_repayment_schedules_id'), 'loan_repayment_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_loan_repayment_schedules_loan_id'), 'loan_repayment_schedules', ['loan_id'], unique=False)
    op.create_index(op.f('ix_loan_repayment_schedules_organisation_id'), 'loan_repayment_schedules', ['organisation_id'], unique=False)
    op.create_table('loan_repayments',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('ledger_entry_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('principal_portion', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('interest_portion', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('penalty_portion', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('received_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['received_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_repayments_id'), 'loan_repayments', ['id'], unique=False)
    op.create_index(op.f('ix_loan_repayments_loan_id'), 'loan_repayments', ['loan_id'], unique=False)
    op.create_index(op.f('ix_loan_repayments_organisation_id'), 'loan_repayments', ['organisation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_repayments_organisation_id'), table_name='loan_repayments')
    op.drop_index(op.f('ix_loan_repayments_loan_id'), table_name='loan_repayments')
    op.drop_index(op.f('ix_loan_repayments_id'), table_name='loan_repayments')
    op.drop_table('loan_repayments')
    op.drop_index(op.f('ix_loan_repayment_schedules_organisation_id'), table_name='loan_repayment_schedules')
    op.drop_index(op.f('ix_loan_repayment_schedules_loan_id'), table_name='loan_repayment_schedules')
    op.drop_index(op.f('ix_loan_repayment_schedules_id'), table_name='loan_repayment_schedules')
    op.drop_table('loan_repayment_schedules')
    op.drop_index(op.f('ix_loan_penalties_organisation_id'), table_name='loan_penalties')
    op.drop_index(op.f('ix_loan_penalties_loan_id'), table_name='loan_penalties')
    op.drop_index(op.f('ix_loan_penalties_id'), table_name='loan_penalties')
    op.drop_table('loan_penalties')
    op.drop_index(op.f('ix_share_transactions_organisation_id'), table_name='share_transactions')
    op.drop_index(op.f('ix_share_transactions_id'), table_name='share_transactions')
    op.drop_index(op.f('ix_share_transactions_account_id'), table_name='share_transactions')
    op.drop_table('share_transactions')
    op.drop_index(op.f('ix_savings_transactions_organisation_id'), table_name='savings_transactions')
    op.drop_index(op.f('ix_savings_transactions_id'), table_name='savings_transactions')
    op.drop_index(op.f('ix_savings_transactions_account_id'), table_name='savings_transactions')
    op.drop_table('savings_transactions')
    op.drop_index(op.f('ix_loans_organisation_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_member_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_index(op.f('ix_loans_branch_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_loan_guarantors_organisation_id'), table_name='loan_guarantors')
    op.drop_index(op.f('ix_loan_guarantors_id'), table_name='loan_guarantors')
    op.drop_index(op.f('ix_loan_guarantors_application_id'), table_name='loan_guarantors')
    op.drop_table('loan_guarantors')
    op.drop_index(op.f('ix_loan_collaterals_organisation_id'), table_name='loan_collaterals')
    op.drop_index(op.f('ix_loan_collaterals_id'), table_name='loan_collaterals')
    op.drop_index(op.f('ix_loan_collaterals_application_id'), table_name='loan_collaterals')
    op.drop_table('loan_collaterals')
    op.drop_index(op.f('ix_ledger_lines_organisation_id'), table_name='ledger_lines')
    op.drop_index(op.f('ix_ledger_lines_id'), table_name='ledger_lines')
    op.drop_index(op.f('ix_ledger_lines_entry_id'), table_name='ledger_lines')
    op.drop_index(op.f('ix_ledger_lines_account_id'), table_name='ledger_lines')
    op.drop_table('ledger_lines')
    op.drop_index(op.f('ix_journal_entries_organisation_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_branch_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_dividend_payments_share_account_id'), table_name='dividend_payments')
    op.drop_index(op.f('ix_dividend_payments_organisation_id'), table_name='dividend_payments')
    op.drop_index(op.f('ix_dividend_payments_id'), table_name='dividend_payments')
    op.drop_index(op.f('ix_dividend_payments_dividend_id'), table_name='dividend_payments')
    op.drop_table('dividend_payments')
    op.drop_table('user_accounts')
    op.drop_table('transactions')
    op.drop_table('profile')
    op.drop_table('login_logs')
    op.drop_index(op.f('ix_loan_applications_organisation_id'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_member_id'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_id'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_branch_id'), table_name='loan_applications')
    op.drop_table('loan_applications')
    op.drop_index(op.f('ix_ledger_entries_organisation_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_branch_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_dividends_organisation_id'), table_name='dividends')
    op.drop_index(op.f('ix_dividends_id'), table_name='dividends')
    op.drop_table('dividends')
    op.drop_table('address')
    op.drop_index(op.f('ix_users_organisation_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_share_accounts_organisation_id'), table_name='share_accounts')
    op.drop_index(op.f('ix_share_accounts_member_id'), table_name='share_accounts')
    op.drop_index(op.f('ix_share_accounts_id'), table_name='share_accounts')
    op.drop_index(op.f('ix_share_accounts_branch_id'), table_name='share_accounts')
    op.drop_table('share_accounts')
    op.drop_index(op.f('ix_savings_accounts_organisation_id'), table_name='savings_accounts')
    op.drop_index(op.f('ix_savings_accounts_member_id'), table_name='savings_accounts')
    op.drop_index(op.f('ix_savings_accounts_id'), table_name='savings_accounts')
    op.drop_index(op.f('ix_savings_accounts_branch_id'), table_name='savings_accounts')
    op.drop_table('savings_accounts')
    op.drop_index(op.f('ix_next_of_kin_member_id'), table_name='next_of_kin')
    op.drop_index(op.f('ix_next_of_kin_id'), table_name='next_of_kin')
    op.drop_table('next_of_kin')
    op.drop_index(op.f('ix_members_organisation_id'), table_name='members')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_index(op.f('ix_members_branch_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_share_products_organisation_id'), table_name='share_products')
    op.drop_index(op.f('ix_share_products_id'), table_name='share_products')
    op.drop_table('share_products')
    op.drop_index(op.f('ix_savings_products_organisation_id'), table_name='savings_products')
    op.drop_index(op.f('ix_savings_products_id'), table_name='savings_products')
    op.drop_table('savings_products')
    op.drop_index(op.f('ix_loan_products_organisation_id'), table_name='loan_products')
    op.drop_index(op.f('ix_loan_products_id'), table_name='loan_products')
    op.drop_table('loan_products')
    op.drop_index(op.f('ix_chart_of_accounts_organisation_id'), table_name='chart_of_accounts')
    op.drop_index(op.f('ix_chart_of_accounts_id'), table_name='chart_of_accounts')
    op.drop_table('chart_of_accounts')
    op.drop_index(op.f('ix_branches_organisation_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_organisations_id'), table_name='organisations')
    op.drop_table('organisations')
    op.drop_table('accounts')
    # ### end Alembic commands ###
