"""loan products

Revision ID: 6d815900e319
Revises: 2dac8f014448
Create Date: 2026-05-21 19:55:28.511467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d815900e319'
down_revision: Union[str, Sequence[str], None] = '2dac8f014448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_products_organisation_id'), table_name='loan_products')
    op.drop_constraint(op.f('loan_products_organisation_id_fkey'), 'loan_products', type_='foreignkey')
    op.drop_column('loan_products', 'organisation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_products', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('loan_products_organisation_id_fkey'), 'loan_products', 'organisations', ['organisation_id'], ['id'])
    op.create_index(op.f('ix_loan_products_organisation_id'), 'loan_products', ['organisation_id'], unique=False)
    # ### end Alembic commands ###
