"""initial db migration

Revision ID: 7427fb8610b1
Revises: 
Create Date: 2026-05-26 22:48:35.725006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7427fb8610b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_channel_configurations',
    sa.Column('channel_code', sa.String(length=50), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=False),
    sa.Column('asset_account_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_account_id'], ['chart_of_accounts.id'], ),
    sa.PrimaryKeyConstraint('channel_code', 'id')
    )
    op.create_index(op.f('ix_payment_channel_configurations_channel_code'), 'payment_channel_configurations', ['channel_code'], unique=True)
    op.create_index(op.f('ix_payment_channel_configurations_id'), 'payment_channel_configurations', ['id'], unique=False)
    op.create_table('mobile_money_transactions',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('provider_response', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mobile_money_transactions_id'), 'mobile_money_transactions', ['id'], unique=False)
    op.drop_index(op.f('ix_branches_organisation_id'), table_name='branches', postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_branches_organisation_id'), 'branches', ['organisation_id'], unique=False)
    op.alter_column('chart_of_accounts', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_chart_of_accounts_organisation_id'), table_name='chart_of_accounts', postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_chart_of_accounts_id'), table_name='chart_of_accounts', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_chart_of_accounts_id'), 'chart_of_accounts', ['id'], unique=False)
    op.drop_constraint(op.f('chart_of_accounts_organisation_id_fkey'), 'chart_of_accounts', type_='foreignkey')
    op.drop_column('chart_of_accounts', 'organisation_id')
    op.drop_index(op.f('ix_dividend_payments_dividend_id'), table_name='dividend_payments', postgresql_ops={'dividend_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_dividend_payments_dividend_id'), 'dividend_payments', ['dividend_id'], unique=False)
    op.drop_index(op.f('ix_dividend_payments_id'), table_name='dividend_payments', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_dividend_payments_id'), 'dividend_payments', ['id'], unique=False)
    op.drop_index(op.f('ix_dividend_payments_organisation_id'), table_name='dividend_payments', postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_dividend_payments_organisation_id'), 'dividend_payments', ['organisation_id'], unique=False)
    op.drop_index(op.f('ix_dividend_payments_share_account_id'), table_name='dividend_payments', postgresql_ops={'share_account_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_dividend_payments_share_account_id'), 'dividend_payments', ['share_account_id'], unique=False)
    op.alter_column('dividend_statuses', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_dividend_statuses_id'), table_name='dividend_statuses', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_dividend_statuses_id'), 'dividend_statuses', ['id'], unique=False)
    op.alter_column('dividends', 'notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_dividends_id'), table_name='dividends', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_dividends_id'), 'dividends', ['id'], unique=False)
    op.drop_index(op.f('ix_dividends_organisation_id'), table_name='dividends', postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_dividends_organisation_id'), 'dividends', ['organisation_id'], unique=False)
    op.alter_column('genders', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_genders_id'), table_name='genders', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_genders_id'), 'genders', ['id'], unique=False)
    op.alter_column('journal_entries', 'narration',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index(op.f('ix_journal_entries_organisation_id'), table_name='journal_entries', postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_journal_entries_branch_id'), table_name='journal_entries', postgresql_ops={'branch_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_journal_entries_branch_id'), 'journal_entries', ['branch_id'], unique=False)
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.drop_constraint(op.f('journal_entries_organisation_id_fkey'), 'journal_entries', type_='foreignkey')
    op.drop_column('journal_entries', 'organisation_id')
    op.alter_column('ledger_account_categories', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ledger_account_categories_id'), table_name='ledger_account_categories', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_ledger_account_categories_id'), 'ledger_account_categories', ['id'], unique=False)
    op.alter_column('ledger_account_types', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ledger_account_types_id'), table_name='ledger_account_types', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_ledger_account_types_id'), 'ledger_account_types', ['id'], unique=False)
    op.alter_column('ledger_dr_crs', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ledger_dr_crs_id'), table_name='ledger_dr_crs', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_ledger_dr_crs_id'), 'ledger_dr_crs', ['id'], unique=False)
    op.alter_column('ledger_entries', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('ledger_entries', 'notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ledger_entries_organisation_id'), table_name='ledger_entries', postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_ledger_entries_branch_id'), table_name='ledger_entries', postgresql_ops={'branch_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_ledger_entries_branch_id'), 'ledger_entries', ['branch_id'], unique=False)
    op.drop_index(op.f('ix_ledger_entries_id'), table_name='ledger_entries', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_ledger_entries_id'), 'ledger_entries', ['id'], unique=False)
    op.drop_constraint(op.f('ledger_entries_organisation_id_fkey'), 'ledger_entries', type_='foreignkey')
    op.drop_column('ledger_entries', 'organisation_id')
    op.alter_column('ledger_entry_statuses', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ledger_entry_statuses_id'), table_name='ledger_entry_statuses', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_ledger_entry_statuses_id'), 'ledger_entry_statuses', ['id'], unique=False)
    op.alter_column('ledger_entry_types', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ledger_entry_types_id'), table_name='ledger_entry_types', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_ledger_entry_types_id'), 'ledger_entry_types', ['id'], unique=False)
    op.alter_column('ledger_lines', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ledger_lines_organisation_id'), table_name='ledger_lines', postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_ledger_lines_account_id'), table_name='ledger_lines', postgresql_ops={'account_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_ledger_lines_account_id'), 'ledger_lines', ['account_id'], unique=False)
    op.drop_index(op.f('ix_ledger_lines_entry_id'), table_name='ledger_lines', postgresql_ops={'entry_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_ledger_lines_entry_id'), 'ledger_lines', ['entry_id'], unique=False)
    op.drop_index(op.f('ix_ledger_lines_id'), table_name='ledger_lines', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_ledger_lines_id'), 'ledger_lines', ['id'], unique=False)
    op.drop_constraint(op.f('ledger_lines_organisation_id_fkey'), 'ledger_lines', type_='foreignkey')
    op.drop_column('ledger_lines', 'organisation_id')
    op.alter_column('loan_application_statuses', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_application_statuses_id'), table_name='loan_application_statuses', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_application_statuses_id'), 'loan_application_statuses', ['id'], unique=False)
    op.alter_column('loan_applications', 'purpose',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('loan_applications', 'rejection_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('loan_applications', 'notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_applications_branch_id'), table_name='loan_applications', postgresql_ops={'branch_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_applications_branch_id'), 'loan_applications', ['branch_id'], unique=False)
    op.drop_index(op.f('ix_loan_applications_id'), table_name='loan_applications', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_applications_id'), 'loan_applications', ['id'], unique=False)
    op.drop_index(op.f('ix_loan_applications_member_id'), table_name='loan_applications', postgresql_ops={'member_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_applications_member_id'), 'loan_applications', ['member_id'], unique=False)
    op.alter_column('loan_collateral_types', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_collateral_types_id'), table_name='loan_collateral_types', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_collateral_types_id'), 'loan_collateral_types', ['id'], unique=False)
    op.alter_column('loan_collaterals', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('loan_collaterals', 'notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_collaterals_application_id'), table_name='loan_collaterals', postgresql_ops={'application_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_collaterals_application_id'), 'loan_collaterals', ['application_id'], unique=False)
    op.drop_index(op.f('ix_loan_collaterals_id'), table_name='loan_collaterals', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_collaterals_id'), 'loan_collaterals', ['id'], unique=False)
    op.alter_column('loan_guarantors', 'notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_guarantors_application_id'), table_name='loan_guarantors', postgresql_ops={'application_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_guarantors_application_id'), 'loan_guarantors', ['application_id'], unique=False)
    op.drop_index(op.f('ix_loan_guarantors_id'), table_name='loan_guarantors', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_guarantors_id'), 'loan_guarantors', ['id'], unique=False)
    op.alter_column('loan_interest_methods', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_interest_methods_id'), table_name='loan_interest_methods', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_interest_methods_id'), 'loan_interest_methods', ['id'], unique=False)
    op.alter_column('loan_penalties', 'notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_penalties_id'), table_name='loan_penalties', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_penalties_id'), 'loan_penalties', ['id'], unique=False)
    op.drop_index(op.f('ix_loan_penalties_loan_id'), table_name='loan_penalties', postgresql_ops={'loan_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_penalties_loan_id'), 'loan_penalties', ['loan_id'], unique=False)
    op.alter_column('loan_penalty_types', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_penalty_types_id'), table_name='loan_penalty_types', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_penalty_types_id'), 'loan_penalty_types', ['id'], unique=False)
    op.add_column('loan_products', sa.Column('loan_receivable_account_id', sa.UUID(), nullable=True))
    op.add_column('loan_products', sa.Column('interest_income_account_id', sa.UUID(), nullable=True))
    op.add_column('loan_products', sa.Column('penalty_income_account_id', sa.UUID(), nullable=True))
    op.add_column('loan_products', sa.Column('processing_fee_account_id', sa.UUID(), nullable=True))
    op.alter_column('loan_products', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_products_id'), table_name='loan_products', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_products_id'), 'loan_products', ['id'], unique=False)
    op.create_foreign_key(None, 'loan_products', 'chart_of_accounts', ['loan_receivable_account_id'], ['id'])
    op.create_foreign_key(None, 'loan_products', 'chart_of_accounts', ['interest_income_account_id'], ['id'])
    op.create_foreign_key(None, 'loan_products', 'chart_of_accounts', ['penalty_income_account_id'], ['id'])
    op.create_foreign_key(None, 'loan_products', 'chart_of_accounts', ['processing_fee_account_id'], ['id'])
    op.alter_column('loan_repayment_frequencies', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_repayment_frequencies_id'), table_name='loan_repayment_frequencies', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_repayment_frequencies_id'), 'loan_repayment_frequencies', ['id'], unique=False)
    op.drop_index(op.f('ix_loan_repayment_schedules_id'), table_name='loan_repayment_schedules', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_repayment_schedules_id'), 'loan_repayment_schedules', ['id'], unique=False)
    op.drop_index(op.f('ix_loan_repayment_schedules_loan_id'), table_name='loan_repayment_schedules', postgresql_ops={'loan_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_repayment_schedules_loan_id'), 'loan_repayment_schedules', ['loan_id'], unique=False)
    op.alter_column('loan_repayments', 'notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_repayments_id'), table_name='loan_repayments', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_repayments_id'), 'loan_repayments', ['id'], unique=False)
    op.drop_index(op.f('ix_loan_repayments_loan_id'), table_name='loan_repayments', postgresql_ops={'loan_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_repayments_loan_id'), 'loan_repayments', ['loan_id'], unique=False)
    op.alter_column('loan_statuses', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_statuses_id'), table_name='loan_statuses', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loan_statuses_id'), 'loan_statuses', ['id'], unique=False)
    op.alter_column('loans', 'notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loans_branch_id'), table_name='loans', postgresql_ops={'branch_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loans_branch_id'), 'loans', ['branch_id'], unique=False)
    op.drop_index(op.f('ix_loans_id'), table_name='loans', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.drop_index(op.f('ix_loans_member_id'), table_name='loans', postgresql_ops={'member_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_loans_member_id'), 'loans', ['member_id'], unique=False)
    op.add_column('login_logs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_login_logs_id'), table_name='login_logs', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_login_logs_id'), 'login_logs', ['id'], unique=False)
    op.drop_constraint(op.f('login_logs_member_id_fkey'), 'login_logs', type_='foreignkey')
    op.create_foreign_key(None, 'login_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('login_logs', 'member_id')
    op.alter_column('marital_statuses', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_marital_statuses_id'), table_name='marital_statuses', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_marital_statuses_id'), 'marital_statuses', ['id'], unique=False)
    op.alter_column('member_statuses', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_member_statuses_id'), table_name='member_statuses', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_member_statuses_id'), 'member_statuses', ['id'], unique=False)
    op.alter_column('members', 'status_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('members', 'physical_address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('members', 'exit_reason',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_members_organisation_id'), table_name='members', postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_members_branch_id'), table_name='members', postgresql_ops={'branch_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_members_branch_id'), 'members', ['branch_id'], unique=False)
    op.drop_index(op.f('ix_members_id'), table_name='members', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.drop_constraint(op.f('ix_members_member_no'), 'members', type_='unique')
    op.create_index(op.f('ix_members_member_no'), 'members', ['member_no'], unique=True)
    op.drop_constraint(op.f('uq_member_no_per_org'), 'members', type_='unique')
    op.create_unique_constraint('uq_member_no_per_org', 'members', ['member_no'])
    op.drop_constraint(op.f('members_organisation_id_fkey'), 'members', type_='foreignkey')
    op.drop_column('members', 'organisation_id')
    op.alter_column('next_of_kin', 'address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_next_of_kin_id'), table_name='next_of_kin', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_next_of_kin_id'), 'next_of_kin', ['id'], unique=False)
    op.drop_index(op.f('ix_next_of_kin_member_id'), table_name='next_of_kin', postgresql_ops={'member_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_next_of_kin_member_id'), 'next_of_kin', ['member_id'], unique=False)
    op.alter_column('organisations', 'address',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_roles_id'), table_name='roles', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.alter_column('savings_account_statuses', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_savings_account_statuses_code'), 'savings_account_statuses', type_='unique')
    op.create_index(op.f('ix_savings_account_statuses_code'), 'savings_account_statuses', ['code'], unique=True)
    op.drop_index(op.f('ix_savings_account_statuses_id'), table_name='savings_account_statuses', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_savings_account_statuses_id'), 'savings_account_statuses', ['id'], unique=False)
    op.alter_column('savings_accounts', 'notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_savings_accounts_branch_id'), table_name='savings_accounts', postgresql_ops={'branch_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_savings_accounts_branch_id'), 'savings_accounts', ['branch_id'], unique=False)
    op.drop_index(op.f('ix_savings_accounts_id'), table_name='savings_accounts', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_savings_accounts_id'), 'savings_accounts', ['id'], unique=False)
    op.drop_index(op.f('ix_savings_accounts_member_id'), table_name='savings_accounts', postgresql_ops={'member_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_savings_accounts_member_id'), 'savings_accounts', ['member_id'], unique=False)
    op.drop_index(op.f('ix_savings_accounts_status_id'), table_name='savings_accounts', postgresql_ops={'status_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_savings_accounts_status_id'), 'savings_accounts', ['status_id'], unique=False)
    op.alter_column('savings_product_types', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_savings_product_types_code'), 'savings_product_types', type_='unique')
    op.create_index(op.f('ix_savings_product_types_code'), 'savings_product_types', ['code'], unique=True)
    op.drop_index(op.f('ix_savings_product_types_id'), table_name='savings_product_types', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_savings_product_types_id'), 'savings_product_types', ['id'], unique=False)
    op.add_column('savings_products', sa.Column('savings_control_account_id', sa.UUID(), nullable=False))
    op.add_column('savings_products', sa.Column('interest_expense_account_id', sa.UUID(), nullable=True))
    op.alter_column('savings_products', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_savings_products_id'), table_name='savings_products', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_savings_products_id'), 'savings_products', ['id'], unique=False)
    op.drop_index(op.f('ix_savings_products_product_type_id'), table_name='savings_products', postgresql_ops={'product_type_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_savings_products_product_type_id'), 'savings_products', ['product_type_id'], unique=False)
    op.create_foreign_key(None, 'savings_products', 'chart_of_accounts', ['savings_control_account_id'], ['id'])
    op.create_foreign_key(None, 'savings_products', 'chart_of_accounts', ['interest_expense_account_id'], ['id'])
    op.alter_column('savings_transactions', 'tx_type_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('savings_transactions', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_savings_transactions_tx_type_id'), table_name='savings_transactions', postgresql_ops={'tx_type_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_savings_transactions_account_id'), table_name='savings_transactions', postgresql_ops={'account_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_savings_transactions_account_id'), 'savings_transactions', ['account_id'], unique=False)
    op.drop_index(op.f('ix_savings_transactions_id'), table_name='savings_transactions', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_savings_transactions_id'), 'savings_transactions', ['id'], unique=False)
    op.drop_column('savings_transactions', 'tx_type')
    op.alter_column('savings_tx_types', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('ix_savings_tx_types_code'), 'savings_tx_types', type_='unique')
    op.create_index(op.f('ix_savings_tx_types_code'), 'savings_tx_types', ['code'], unique=True)
    op.drop_index(op.f('ix_savings_tx_types_id'), table_name='savings_tx_types', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_savings_tx_types_id'), 'savings_tx_types', ['id'], unique=False)
    op.drop_index(op.f('ix_share_accounts_branch_id'), table_name='share_accounts', postgresql_ops={'branch_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_share_accounts_branch_id'), 'share_accounts', ['branch_id'], unique=False)
    op.drop_index(op.f('ix_share_accounts_id'), table_name='share_accounts', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_share_accounts_id'), 'share_accounts', ['id'], unique=False)
    op.drop_index(op.f('ix_share_accounts_member_id'), table_name='share_accounts', postgresql_ops={'member_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_share_accounts_member_id'), 'share_accounts', ['member_id'], unique=False)
    op.drop_index(op.f('ix_share_accounts_organisation_id'), table_name='share_accounts', postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_share_accounts_organisation_id'), 'share_accounts', ['organisation_id'], unique=False)
    op.alter_column('share_product_types', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_share_product_types_id'), table_name='share_product_types', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_share_product_types_id'), 'share_product_types', ['id'], unique=False)
    op.add_column('share_products', sa.Column('share_capital_account_id', sa.UUID(), nullable=True))
    op.add_column('share_products', sa.Column('dividend_expense_account_id', sa.UUID(), nullable=True))
    op.add_column('share_products', sa.Column('dividend_payable_account_id', sa.UUID(), nullable=True))
    op.alter_column('share_products', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_share_products_id'), table_name='share_products', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_share_products_id'), 'share_products', ['id'], unique=False)
    op.drop_index(op.f('ix_share_products_organisation_id'), table_name='share_products', postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_share_products_organisation_id'), 'share_products', ['organisation_id'], unique=False)
    op.create_foreign_key(None, 'share_products', 'chart_of_accounts', ['share_capital_account_id'], ['id'])
    op.create_foreign_key(None, 'share_products', 'chart_of_accounts', ['dividend_expense_account_id'], ['id'])
    op.create_foreign_key(None, 'share_products', 'chart_of_accounts', ['dividend_payable_account_id'], ['id'])
    op.alter_column('share_transaction_types', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_share_transaction_types_id'), table_name='share_transaction_types', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_share_transaction_types_id'), 'share_transaction_types', ['id'], unique=False)
    op.alter_column('share_transactions', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_share_transactions_account_id'), table_name='share_transactions', postgresql_ops={'account_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_share_transactions_account_id'), 'share_transactions', ['account_id'], unique=False)
    op.drop_index(op.f('ix_share_transactions_id'), table_name='share_transactions', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_share_transactions_id'), 'share_transactions', ['id'], unique=False)
    op.drop_index(op.f('ix_share_transactions_organisation_id'), table_name='share_transactions', postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_share_transactions_organisation_id'), 'share_transactions', ['organisation_id'], unique=False)
    op.alter_column('user_types', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_types_id'), table_name='user_types', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_user_types_id'), 'user_types', ['id'], unique=False)
    op.add_column('users', sa.Column('role_name', sa.String(length=15), nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users', postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_constraint(op.f('uq_user_email_per_org'), 'users', type_='unique')
    op.create_unique_constraint('uq_user_email_per_org', 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['role_name'])
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_organisation_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_name'], ['role'], ondelete='RESTRICT')
    op.drop_column('users', 'organisation_id')
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_organisation_id_fkey'), 'users', 'organisations', ['organisation_id'], ['id'])
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint('uq_user_email_per_org', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_user_email_per_org'), 'users', ['organisation_id', 'email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_column('users', 'role_name')
    op.drop_index(op.f('ix_user_types_id'), table_name='user_types')
    op.create_index(op.f('ix_user_types_id'), 'user_types', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('user_types', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_share_transactions_organisation_id'), table_name='share_transactions')
    op.create_index(op.f('ix_share_transactions_organisation_id'), 'share_transactions', [sa.literal_column('organisation_id NULLS FIRST')], unique=False, postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_share_transactions_id'), table_name='share_transactions')
    op.create_index(op.f('ix_share_transactions_id'), 'share_transactions', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_share_transactions_account_id'), table_name='share_transactions')
    op.create_index(op.f('ix_share_transactions_account_id'), 'share_transactions', [sa.literal_column('account_id NULLS FIRST')], unique=False, postgresql_ops={'account_id': None}, postgresql_using='prefix')
    op.alter_column('share_transactions', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_share_transaction_types_id'), table_name='share_transaction_types')
    op.create_index(op.f('ix_share_transaction_types_id'), 'share_transaction_types', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('share_transaction_types', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'share_products', type_='foreignkey')
    op.drop_constraint(None, 'share_products', type_='foreignkey')
    op.drop_constraint(None, 'share_products', type_='foreignkey')
    op.drop_index(op.f('ix_share_products_organisation_id'), table_name='share_products')
    op.create_index(op.f('ix_share_products_organisation_id'), 'share_products', [sa.literal_column('organisation_id NULLS FIRST')], unique=False, postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_share_products_id'), table_name='share_products')
    op.create_index(op.f('ix_share_products_id'), 'share_products', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('share_products', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('share_products', 'dividend_payable_account_id')
    op.drop_column('share_products', 'dividend_expense_account_id')
    op.drop_column('share_products', 'share_capital_account_id')
    op.drop_index(op.f('ix_share_product_types_id'), table_name='share_product_types')
    op.create_index(op.f('ix_share_product_types_id'), 'share_product_types', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('share_product_types', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_share_accounts_organisation_id'), table_name='share_accounts')
    op.create_index(op.f('ix_share_accounts_organisation_id'), 'share_accounts', [sa.literal_column('organisation_id NULLS FIRST')], unique=False, postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_share_accounts_member_id'), table_name='share_accounts')
    op.create_index(op.f('ix_share_accounts_member_id'), 'share_accounts', [sa.literal_column('member_id NULLS FIRST')], unique=False, postgresql_ops={'member_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_share_accounts_id'), table_name='share_accounts')
    op.create_index(op.f('ix_share_accounts_id'), 'share_accounts', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_share_accounts_branch_id'), table_name='share_accounts')
    op.create_index(op.f('ix_share_accounts_branch_id'), 'share_accounts', [sa.literal_column('branch_id NULLS FIRST')], unique=False, postgresql_ops={'branch_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_savings_tx_types_id'), table_name='savings_tx_types')
    op.create_index(op.f('ix_savings_tx_types_id'), 'savings_tx_types', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_savings_tx_types_code'), table_name='savings_tx_types')
    op.create_unique_constraint(op.f('ix_savings_tx_types_code'), 'savings_tx_types', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('savings_tx_types', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('savings_transactions', sa.Column('tx_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_savings_transactions_id'), table_name='savings_transactions')
    op.create_index(op.f('ix_savings_transactions_id'), 'savings_transactions', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_savings_transactions_account_id'), table_name='savings_transactions')
    op.create_index(op.f('ix_savings_transactions_account_id'), 'savings_transactions', [sa.literal_column('account_id NULLS FIRST')], unique=False, postgresql_ops={'account_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_savings_transactions_tx_type_id'), 'savings_transactions', [sa.literal_column('tx_type_id NULLS FIRST')], unique=False, postgresql_ops={'tx_type_id': None}, postgresql_using='prefix')
    op.alter_column('savings_transactions', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('savings_transactions', 'tx_type_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'savings_products', type_='foreignkey')
    op.drop_constraint(None, 'savings_products', type_='foreignkey')
    op.drop_index(op.f('ix_savings_products_product_type_id'), table_name='savings_products')
    op.create_index(op.f('ix_savings_products_product_type_id'), 'savings_products', [sa.literal_column('product_type_id NULLS FIRST')], unique=False, postgresql_ops={'product_type_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_savings_products_id'), table_name='savings_products')
    op.create_index(op.f('ix_savings_products_id'), 'savings_products', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('savings_products', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('savings_products', 'interest_expense_account_id')
    op.drop_column('savings_products', 'savings_control_account_id')
    op.drop_index(op.f('ix_savings_product_types_id'), table_name='savings_product_types')
    op.create_index(op.f('ix_savings_product_types_id'), 'savings_product_types', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_savings_product_types_code'), table_name='savings_product_types')
    op.create_unique_constraint(op.f('ix_savings_product_types_code'), 'savings_product_types', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('savings_product_types', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_savings_accounts_status_id'), table_name='savings_accounts')
    op.create_index(op.f('ix_savings_accounts_status_id'), 'savings_accounts', [sa.literal_column('status_id NULLS FIRST')], unique=False, postgresql_ops={'status_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_savings_accounts_member_id'), table_name='savings_accounts')
    op.create_index(op.f('ix_savings_accounts_member_id'), 'savings_accounts', [sa.literal_column('member_id NULLS FIRST')], unique=False, postgresql_ops={'member_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_savings_accounts_id'), table_name='savings_accounts')
    op.create_index(op.f('ix_savings_accounts_id'), 'savings_accounts', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_savings_accounts_branch_id'), table_name='savings_accounts')
    op.create_index(op.f('ix_savings_accounts_branch_id'), 'savings_accounts', [sa.literal_column('branch_id NULLS FIRST')], unique=False, postgresql_ops={'branch_id': None}, postgresql_using='prefix')
    op.alter_column('savings_accounts', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_savings_account_statuses_id'), table_name='savings_account_statuses')
    op.create_index(op.f('ix_savings_account_statuses_id'), 'savings_account_statuses', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_savings_account_statuses_code'), table_name='savings_account_statuses')
    op.create_unique_constraint(op.f('ix_savings_account_statuses_code'), 'savings_account_statuses', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('savings_account_statuses', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.create_index(op.f('ix_roles_id'), 'roles', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('organisations', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_next_of_kin_member_id'), table_name='next_of_kin')
    op.create_index(op.f('ix_next_of_kin_member_id'), 'next_of_kin', [sa.literal_column('member_id NULLS FIRST')], unique=False, postgresql_ops={'member_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_next_of_kin_id'), table_name='next_of_kin')
    op.create_index(op.f('ix_next_of_kin_id'), 'next_of_kin', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('next_of_kin', 'address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('members', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('members_organisation_id_fkey'), 'members', 'organisations', ['organisation_id'], ['id'])
    op.drop_constraint('uq_member_no_per_org', 'members', type_='unique')
    op.create_unique_constraint(op.f('uq_member_no_per_org'), 'members', ['organisation_id', 'member_no'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_members_member_no'), table_name='members')
    op.create_unique_constraint(op.f('ix_members_member_no'), 'members', ['member_no'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.create_index(op.f('ix_members_id'), 'members', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_members_branch_id'), table_name='members')
    op.create_index(op.f('ix_members_branch_id'), 'members', [sa.literal_column('branch_id NULLS FIRST')], unique=False, postgresql_ops={'branch_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_members_organisation_id'), 'members', [sa.literal_column('organisation_id NULLS FIRST')], unique=False, postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.alter_column('members', 'exit_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('members', 'physical_address',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('members', 'status_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_member_statuses_id'), table_name='member_statuses')
    op.create_index(op.f('ix_member_statuses_id'), 'member_statuses', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('member_statuses', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_marital_statuses_id'), table_name='marital_statuses')
    op.create_index(op.f('ix_marital_statuses_id'), 'marital_statuses', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('marital_statuses', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('login_logs', sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'login_logs', type_='foreignkey')
    op.create_foreign_key(op.f('login_logs_member_id_fkey'), 'login_logs', 'users', ['member_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_login_logs_id'), table_name='login_logs')
    op.create_index(op.f('ix_login_logs_id'), 'login_logs', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_column('login_logs', 'user_id')
    op.drop_index(op.f('ix_loans_member_id'), table_name='loans')
    op.create_index(op.f('ix_loans_member_id'), 'loans', [sa.literal_column('member_id NULLS FIRST')], unique=False, postgresql_ops={'member_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.create_index(op.f('ix_loans_id'), 'loans', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_loans_branch_id'), table_name='loans')
    op.create_index(op.f('ix_loans_branch_id'), 'loans', [sa.literal_column('branch_id NULLS FIRST')], unique=False, postgresql_ops={'branch_id': None}, postgresql_using='prefix')
    op.alter_column('loans', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_statuses_id'), table_name='loan_statuses')
    op.create_index(op.f('ix_loan_statuses_id'), 'loan_statuses', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('loan_statuses', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_repayments_loan_id'), table_name='loan_repayments')
    op.create_index(op.f('ix_loan_repayments_loan_id'), 'loan_repayments', [sa.literal_column('loan_id NULLS FIRST')], unique=False, postgresql_ops={'loan_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_loan_repayments_id'), table_name='loan_repayments')
    op.create_index(op.f('ix_loan_repayments_id'), 'loan_repayments', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('loan_repayments', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_repayment_schedules_loan_id'), table_name='loan_repayment_schedules')
    op.create_index(op.f('ix_loan_repayment_schedules_loan_id'), 'loan_repayment_schedules', [sa.literal_column('loan_id NULLS FIRST')], unique=False, postgresql_ops={'loan_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_loan_repayment_schedules_id'), table_name='loan_repayment_schedules')
    op.create_index(op.f('ix_loan_repayment_schedules_id'), 'loan_repayment_schedules', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_loan_repayment_frequencies_id'), table_name='loan_repayment_frequencies')
    op.create_index(op.f('ix_loan_repayment_frequencies_id'), 'loan_repayment_frequencies', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('loan_repayment_frequencies', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'loan_products', type_='foreignkey')
    op.drop_constraint(None, 'loan_products', type_='foreignkey')
    op.drop_constraint(None, 'loan_products', type_='foreignkey')
    op.drop_constraint(None, 'loan_products', type_='foreignkey')
    op.drop_index(op.f('ix_loan_products_id'), table_name='loan_products')
    op.create_index(op.f('ix_loan_products_id'), 'loan_products', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('loan_products', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('loan_products', 'processing_fee_account_id')
    op.drop_column('loan_products', 'penalty_income_account_id')
    op.drop_column('loan_products', 'interest_income_account_id')
    op.drop_column('loan_products', 'loan_receivable_account_id')
    op.drop_index(op.f('ix_loan_penalty_types_id'), table_name='loan_penalty_types')
    op.create_index(op.f('ix_loan_penalty_types_id'), 'loan_penalty_types', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('loan_penalty_types', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_penalties_loan_id'), table_name='loan_penalties')
    op.create_index(op.f('ix_loan_penalties_loan_id'), 'loan_penalties', [sa.literal_column('loan_id NULLS FIRST')], unique=False, postgresql_ops={'loan_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_loan_penalties_id'), table_name='loan_penalties')
    op.create_index(op.f('ix_loan_penalties_id'), 'loan_penalties', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('loan_penalties', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_interest_methods_id'), table_name='loan_interest_methods')
    op.create_index(op.f('ix_loan_interest_methods_id'), 'loan_interest_methods', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('loan_interest_methods', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_guarantors_id'), table_name='loan_guarantors')
    op.create_index(op.f('ix_loan_guarantors_id'), 'loan_guarantors', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_loan_guarantors_application_id'), table_name='loan_guarantors')
    op.create_index(op.f('ix_loan_guarantors_application_id'), 'loan_guarantors', [sa.literal_column('application_id NULLS FIRST')], unique=False, postgresql_ops={'application_id': None}, postgresql_using='prefix')
    op.alter_column('loan_guarantors', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_collaterals_id'), table_name='loan_collaterals')
    op.create_index(op.f('ix_loan_collaterals_id'), 'loan_collaterals', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_loan_collaterals_application_id'), table_name='loan_collaterals')
    op.create_index(op.f('ix_loan_collaterals_application_id'), 'loan_collaterals', [sa.literal_column('application_id NULLS FIRST')], unique=False, postgresql_ops={'application_id': None}, postgresql_using='prefix')
    op.alter_column('loan_collaterals', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('loan_collaterals', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_loan_collateral_types_id'), table_name='loan_collateral_types')
    op.create_index(op.f('ix_loan_collateral_types_id'), 'loan_collateral_types', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('loan_collateral_types', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_applications_member_id'), table_name='loan_applications')
    op.create_index(op.f('ix_loan_applications_member_id'), 'loan_applications', [sa.literal_column('member_id NULLS FIRST')], unique=False, postgresql_ops={'member_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_loan_applications_id'), table_name='loan_applications')
    op.create_index(op.f('ix_loan_applications_id'), 'loan_applications', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_loan_applications_branch_id'), table_name='loan_applications')
    op.create_index(op.f('ix_loan_applications_branch_id'), 'loan_applications', [sa.literal_column('branch_id NULLS FIRST')], unique=False, postgresql_ops={'branch_id': None}, postgresql_using='prefix')
    op.alter_column('loan_applications', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('loan_applications', 'rejection_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('loan_applications', 'purpose',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_loan_application_statuses_id'), table_name='loan_application_statuses')
    op.create_index(op.f('ix_loan_application_statuses_id'), 'loan_application_statuses', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('loan_application_statuses', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('ledger_lines', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('ledger_lines_organisation_id_fkey'), 'ledger_lines', 'organisations', ['organisation_id'], ['id'])
    op.drop_index(op.f('ix_ledger_lines_id'), table_name='ledger_lines')
    op.create_index(op.f('ix_ledger_lines_id'), 'ledger_lines', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_ledger_lines_entry_id'), table_name='ledger_lines')
    op.create_index(op.f('ix_ledger_lines_entry_id'), 'ledger_lines', [sa.literal_column('entry_id NULLS FIRST')], unique=False, postgresql_ops={'entry_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_ledger_lines_account_id'), table_name='ledger_lines')
    op.create_index(op.f('ix_ledger_lines_account_id'), 'ledger_lines', [sa.literal_column('account_id NULLS FIRST')], unique=False, postgresql_ops={'account_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_ledger_lines_organisation_id'), 'ledger_lines', [sa.literal_column('organisation_id NULLS FIRST')], unique=False, postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.alter_column('ledger_lines', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ledger_entry_types_id'), table_name='ledger_entry_types')
    op.create_index(op.f('ix_ledger_entry_types_id'), 'ledger_entry_types', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('ledger_entry_types', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ledger_entry_statuses_id'), table_name='ledger_entry_statuses')
    op.create_index(op.f('ix_ledger_entry_statuses_id'), 'ledger_entry_statuses', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('ledger_entry_statuses', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('ledger_entries', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('ledger_entries_organisation_id_fkey'), 'ledger_entries', 'organisations', ['organisation_id'], ['id'])
    op.drop_index(op.f('ix_ledger_entries_id'), table_name='ledger_entries')
    op.create_index(op.f('ix_ledger_entries_id'), 'ledger_entries', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_ledger_entries_branch_id'), table_name='ledger_entries')
    op.create_index(op.f('ix_ledger_entries_branch_id'), 'ledger_entries', [sa.literal_column('branch_id NULLS FIRST')], unique=False, postgresql_ops={'branch_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_ledger_entries_organisation_id'), 'ledger_entries', [sa.literal_column('organisation_id NULLS FIRST')], unique=False, postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.alter_column('ledger_entries', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('ledger_entries', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ledger_dr_crs_id'), table_name='ledger_dr_crs')
    op.create_index(op.f('ix_ledger_dr_crs_id'), 'ledger_dr_crs', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('ledger_dr_crs', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ledger_account_types_id'), table_name='ledger_account_types')
    op.create_index(op.f('ix_ledger_account_types_id'), 'ledger_account_types', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('ledger_account_types', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ledger_account_categories_id'), table_name='ledger_account_categories')
    op.create_index(op.f('ix_ledger_account_categories_id'), 'ledger_account_categories', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('ledger_account_categories', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('journal_entries', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('journal_entries_organisation_id_fkey'), 'journal_entries', 'organisations', ['organisation_id'], ['id'])
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_journal_entries_branch_id'), table_name='journal_entries')
    op.create_index(op.f('ix_journal_entries_branch_id'), 'journal_entries', [sa.literal_column('branch_id NULLS FIRST')], unique=False, postgresql_ops={'branch_id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_journal_entries_organisation_id'), 'journal_entries', [sa.literal_column('organisation_id NULLS FIRST')], unique=False, postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.alter_column('journal_entries', 'narration',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_genders_id'), table_name='genders')
    op.create_index(op.f('ix_genders_id'), 'genders', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('genders', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_dividends_organisation_id'), table_name='dividends')
    op.create_index(op.f('ix_dividends_organisation_id'), 'dividends', [sa.literal_column('organisation_id NULLS FIRST')], unique=False, postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_dividends_id'), table_name='dividends')
    op.create_index(op.f('ix_dividends_id'), 'dividends', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('dividends', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_dividend_statuses_id'), table_name='dividend_statuses')
    op.create_index(op.f('ix_dividend_statuses_id'), 'dividend_statuses', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.alter_column('dividend_statuses', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_dividend_payments_share_account_id'), table_name='dividend_payments')
    op.create_index(op.f('ix_dividend_payments_share_account_id'), 'dividend_payments', [sa.literal_column('share_account_id NULLS FIRST')], unique=False, postgresql_ops={'share_account_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_dividend_payments_organisation_id'), table_name='dividend_payments')
    op.create_index(op.f('ix_dividend_payments_organisation_id'), 'dividend_payments', [sa.literal_column('organisation_id NULLS FIRST')], unique=False, postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_dividend_payments_id'), table_name='dividend_payments')
    op.create_index(op.f('ix_dividend_payments_id'), 'dividend_payments', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_dividend_payments_dividend_id'), table_name='dividend_payments')
    op.create_index(op.f('ix_dividend_payments_dividend_id'), 'dividend_payments', [sa.literal_column('dividend_id NULLS FIRST')], unique=False, postgresql_ops={'dividend_id': None}, postgresql_using='prefix')
    op.add_column('chart_of_accounts', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('chart_of_accounts_organisation_id_fkey'), 'chart_of_accounts', 'organisations', ['organisation_id'], ['id'])
    op.drop_index(op.f('ix_chart_of_accounts_id'), table_name='chart_of_accounts')
    op.create_index(op.f('ix_chart_of_accounts_id'), 'chart_of_accounts', [sa.literal_column('id NULLS FIRST')], unique=False, postgresql_ops={'id': None}, postgresql_using='prefix')
    op.create_index(op.f('ix_chart_of_accounts_organisation_id'), 'chart_of_accounts', [sa.literal_column('organisation_id NULLS FIRST')], unique=False, postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.alter_column('chart_of_accounts', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_branches_organisation_id'), table_name='branches')
    op.create_index(op.f('ix_branches_organisation_id'), 'branches', [sa.literal_column('organisation_id NULLS FIRST')], unique=False, postgresql_ops={'organisation_id': None}, postgresql_using='prefix')
    op.drop_index(op.f('ix_mobile_money_transactions_id'), table_name='mobile_money_transactions')
    op.drop_table('mobile_money_transactions')
    op.drop_index(op.f('ix_payment_channel_configurations_id'), table_name='payment_channel_configurations')
    op.drop_index(op.f('ix_payment_channel_configurations_channel_code'), table_name='payment_channel_configurations')
    op.drop_table('payment_channel_configurations')
    # ### end Alembic commands ###
