"""payments

Revision ID: 76087bf3177b
Revises: 0fe7fca80138
Create Date: 2026-05-23 21:56:37.540893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76087bf3177b'
down_revision: Union[str, Sequence[str], None] = '0fe7fca80138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema securely handling existing row data constraints."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Create the payment configurations table (Safe to build instantly)
    op.create_table('payment_channel_configurations',
    sa.Column('channel_code', sa.String(length=50), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=False),
    sa.Column('asset_account_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_account_id'], ['chart_of_accounts.id'], ),
    sa.PrimaryKeyConstraint('channel_code', 'id')
    )
    op.create_index(op.f('ix_payment_channel_configurations_channel_code'), 'payment_channel_configurations', ['channel_code'], unique=True)
    op.create_index(op.f('ix_payment_channel_configurations_id'), 'payment_channel_configurations', ['id'], unique=False)
    
    # 2. Add columns to savings_products as NULLABLE initially to avoid crashes
    op.add_column('savings_products', sa.Column('savings_control_account_id', sa.UUID(), nullable=True))
    op.add_column('savings_products', sa.Column('interest_expense_account_id', sa.UUID(), nullable=True))
    

    fallback_gl_uuid = "6da13edb-1253-497f-95d2-2e6b272d168f"
    
    op.execute(
        f"UPDATE savings_products SET savings_control_account_id = '{fallback_gl_uuid}' WHERE savings_control_account_id IS NULL"
    )
    
    op.alter_column(
        'savings_products', 
        'savings_control_account_id',
        existing_type=sa.UUID(),
        nullable=False
    )
    
    # 5. Create foreign key connections securely
    op.create_foreign_key(None, 'savings_products', 'chart_of_accounts', ['savings_control_account_id'], ['id'])
    op.create_foreign_key(None, 'savings_products', 'chart_of_accounts', ['interest_expense_account_id'], ['id'])
    
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'savings_products', type_='foreignkey')
    op.drop_constraint(None, 'savings_products', type_='foreignkey')
    op.drop_column('savings_products', 'interest_expense_account_id')
    op.drop_column('savings_products', 'savings_control_account_id')
    op.drop_index(op.f('ix_payment_channel_configurations_id'), table_name='payment_channel_configurations')
    op.drop_index(op.f('ix_payment_channel_configurations_channel_code'), table_name='payment_channel_configurations')
    op.drop_table('payment_channel_configurations')
    # ### end Alembic commands ###
