"""saving_user_fix

Revision ID: 7c677217b709
Revises: a9dc5daea176
Create Date: 2026-05-23 23:29:52.686831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c677217b709'
down_revision: Union[str, Sequence[str], None] = 'a9dc5daea176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('savings_transactions_processed_by_id_fkey'), 'savings_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'savings_transactions', 'users', ['processed_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'savings_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('savings_transactions_processed_by_id_fkey'), 'savings_transactions', 'members', ['processed_by_id'], ['id'])
    # ### end Alembic commands ###
