"""changes

Revision ID: 8a1021d710fb
Revises: 602c1fbbe48b
Create Date: 2026-05-17 18:37:25.835276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a1021d710fb'
down_revision: Union[str, Sequence[str], None] = '602c1fbbe48b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_table('address')
    op.drop_table('user_accounts')
    op.add_column('login_logs', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('login_logs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('login_logs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('login_logs', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_login_logs_id'), 'login_logs', ['id'], unique=False)
    op.add_column('members', sa.Column('country', sa.Text(), nullable=True))
    op.drop_column('members', 'physical_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('physical_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('members', 'country')
    op.drop_index(op.f('ix_login_logs_id'), table_name='login_logs')
    op.drop_column('login_logs', 'is_deleted')
    op.drop_column('login_logs', 'updated_at')
    op.drop_column('login_logs', 'created_at')
    op.drop_column('login_logs', 'id')
    op.create_table('user_accounts',
    sa.Column('user_account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_account_created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_account_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], name=op.f('user_accounts_account_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['users.member_id'], name=op.f('user_accounts_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_account_id', name=op.f('user_accounts_pkey'))
    )
    op.create_table('address',
    sa.Column('address_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nationality', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('district', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('sub_county', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('parish', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('village', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('postal_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('address_created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('address_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['users.member_id'], name=op.f('address_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address_id', name=op.f('address_pkey')),
    sa.UniqueConstraint('member_id', name=op.f('address_member_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('profile',
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('id_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('occupation', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('monthly_income', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('marital_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('employer_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('primary_language', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_avatar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('profile_created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('profile_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['users.member_id'], name=op.f('profile_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', name=op.f('profile_pkey')),
    sa.UniqueConstraint('id_number', name=op.f('profile_id_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('member_id', name=op.f('profile_member_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('phone_number', name=op.f('profile_phone_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
