"""savings

Revision ID: a50fdbd8eb69
Revises: c0e4745b64f6
Create Date: 2026-05-19 15:16:21.021779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a50fdbd8eb69'
down_revision: Union[str, Sequence[str], None] = 'c0e4745b64f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_account_statuses',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_account_statuses_code'), 'savings_account_statuses', ['code'], unique=True)
    op.create_index(op.f('ix_savings_account_statuses_id'), 'savings_account_statuses', ['id'], unique=False)
    op.create_table('savings_product_types',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_product_types_code'), 'savings_product_types', ['code'], unique=True)
    op.create_index(op.f('ix_savings_product_types_id'), 'savings_product_types', ['id'], unique=False)
    op.create_table('savings_tx_types',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_tx_types_code'), 'savings_tx_types', ['code'], unique=True)
    op.create_index(op.f('ix_savings_tx_types_id'), 'savings_tx_types', ['id'], unique=False)
    op.add_column('savings_accounts', sa.Column('status_id', sa.UUID(), nullable=True))
    op.alter_column('savings_accounts', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'DORMANT', 'FROZEN', 'CLOSED', name='savingsaccountstatusenum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_savings_accounts_status_id'), 'savings_accounts', ['status_id'], unique=False)
    op.create_foreign_key(None, 'savings_accounts', 'savings_account_statuses', ['status_id'], ['id'])
    op.add_column('savings_products', sa.Column('product_type_id', sa.UUID(), nullable=True))
    op.alter_column('savings_products', 'product_type',
               existing_type=postgresql.ENUM('ORDINARY', 'FIXED_DEPOSIT', 'GOAL', 'EMERGENCY', 'CHRISTMAS', name='savingsproducttypeenum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_savings_products_product_type_id'), 'savings_products', ['product_type_id'], unique=False)
    op.create_foreign_key(None, 'savings_products', 'savings_product_types', ['product_type_id'], ['id'])
    op.add_column('savings_transactions', sa.Column('tx_type_id', sa.UUID(), nullable=True))
    op.alter_column('savings_transactions', 'tx_type',
               existing_type=postgresql.ENUM('DEPOSIT', 'WITHDRAWAL', 'INTEREST', 'CHARGE', 'TRANSFER', name='savingstxtypeenum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_savings_transactions_tx_type_id'), 'savings_transactions', ['tx_type_id'], unique=False)
    op.create_foreign_key(None, 'savings_transactions', 'savings_tx_types', ['tx_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'savings_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_savings_transactions_tx_type_id'), table_name='savings_transactions')
    op.alter_column('savings_transactions', 'tx_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('DEPOSIT', 'WITHDRAWAL', 'INTEREST', 'CHARGE', 'TRANSFER', name='savingstxtypeenum'),
               existing_nullable=False)
    op.drop_column('savings_transactions', 'tx_type_id')
    op.drop_constraint(None, 'savings_products', type_='foreignkey')
    op.drop_index(op.f('ix_savings_products_product_type_id'), table_name='savings_products')
    op.alter_column('savings_products', 'product_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('ORDINARY', 'FIXED_DEPOSIT', 'GOAL', 'EMERGENCY', 'CHRISTMAS', name='savingsproducttypeenum'),
               existing_nullable=False)
    op.drop_column('savings_products', 'product_type_id')
    op.drop_constraint(None, 'savings_accounts', type_='foreignkey')
    op.drop_index(op.f('ix_savings_accounts_status_id'), table_name='savings_accounts')
    op.alter_column('savings_accounts', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('ACTIVE', 'DORMANT', 'FROZEN', 'CLOSED', name='savingsaccountstatusenum'),
               existing_nullable=False)
    op.drop_column('savings_accounts', 'status_id')
    op.drop_index(op.f('ix_savings_tx_types_id'), table_name='savings_tx_types')
    op.drop_index(op.f('ix_savings_tx_types_code'), table_name='savings_tx_types')
    op.drop_table('savings_tx_types')
    op.drop_index(op.f('ix_savings_product_types_id'), table_name='savings_product_types')
    op.drop_index(op.f('ix_savings_product_types_code'), table_name='savings_product_types')
    op.drop_table('savings_product_types')
    op.drop_index(op.f('ix_savings_account_statuses_id'), table_name='savings_account_statuses')
    op.drop_index(op.f('ix_savings_account_statuses_code'), table_name='savings_account_statuses')
    op.drop_table('savings_account_statuses')
    # ### end Alembic commands ###
