"""added_member_id_to_transaction

Revision ID: ae463541fb90
Revises: 0b89886c2f03
Create Date: 2026-05-27 19:40:37.519786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae463541fb90'
down_revision: Union[str, Sequence[str], None] = '0b89886c2f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings_transactions', sa.Column('member_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'savings_transactions', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'savings_transactions', type_='foreignkey')
    op.drop_column('savings_transactions', 'member_id')
    # ### end Alembic commands ###
