"""clear organisation id

Revision ID: ba2002681fb8
Revises: 6d815900e319
Create Date: 2026-05-21 20:03:56.793283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2002681fb8'
down_revision: Union[str, Sequence[str], None] = '6d815900e319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loan_applications_organisation_id'), table_name='loan_applications')
    op.drop_constraint(op.f('loan_applications_organisation_id_fkey'), 'loan_applications', type_='foreignkey')
    op.drop_column('loan_applications', 'organisation_id')
    op.drop_index(op.f('ix_loan_collaterals_organisation_id'), table_name='loan_collaterals')
    op.drop_constraint(op.f('loan_collaterals_organisation_id_fkey'), 'loan_collaterals', type_='foreignkey')
    op.drop_column('loan_collaterals', 'organisation_id')
    op.drop_index(op.f('ix_loan_guarantors_organisation_id'), table_name='loan_guarantors')
    op.drop_constraint(op.f('loan_guarantors_organisation_id_fkey'), 'loan_guarantors', type_='foreignkey')
    op.drop_column('loan_guarantors', 'organisation_id')
    op.drop_index(op.f('ix_loan_penalties_organisation_id'), table_name='loan_penalties')
    op.drop_constraint(op.f('loan_penalties_organisation_id_fkey'), 'loan_penalties', type_='foreignkey')
    op.drop_column('loan_penalties', 'organisation_id')
    op.drop_index(op.f('ix_loan_repayment_schedules_organisation_id'), table_name='loan_repayment_schedules')
    op.drop_constraint(op.f('loan_repayment_schedules_organisation_id_fkey'), 'loan_repayment_schedules', type_='foreignkey')
    op.drop_column('loan_repayment_schedules', 'organisation_id')
    op.drop_index(op.f('ix_loan_repayments_organisation_id'), table_name='loan_repayments')
    op.drop_constraint(op.f('loan_repayments_organisation_id_fkey'), 'loan_repayments', type_='foreignkey')
    op.drop_column('loan_repayments', 'organisation_id')
    op.drop_index(op.f('ix_loans_organisation_id'), table_name='loans')
    op.drop_constraint(op.f('loans_organisation_id_fkey'), 'loans', type_='foreignkey')
    op.drop_column('loans', 'organisation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('loans_organisation_id_fkey'), 'loans', 'organisations', ['organisation_id'], ['id'])
    op.create_index(op.f('ix_loans_organisation_id'), 'loans', ['organisation_id'], unique=False)
    op.add_column('loan_repayments', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('loan_repayments_organisation_id_fkey'), 'loan_repayments', 'organisations', ['organisation_id'], ['id'])
    op.create_index(op.f('ix_loan_repayments_organisation_id'), 'loan_repayments', ['organisation_id'], unique=False)
    op.add_column('loan_repayment_schedules', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('loan_repayment_schedules_organisation_id_fkey'), 'loan_repayment_schedules', 'organisations', ['organisation_id'], ['id'])
    op.create_index(op.f('ix_loan_repayment_schedules_organisation_id'), 'loan_repayment_schedules', ['organisation_id'], unique=False)
    op.add_column('loan_penalties', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('loan_penalties_organisation_id_fkey'), 'loan_penalties', 'organisations', ['organisation_id'], ['id'])
    op.create_index(op.f('ix_loan_penalties_organisation_id'), 'loan_penalties', ['organisation_id'], unique=False)
    op.add_column('loan_guarantors', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('loan_guarantors_organisation_id_fkey'), 'loan_guarantors', 'organisations', ['organisation_id'], ['id'])
    op.create_index(op.f('ix_loan_guarantors_organisation_id'), 'loan_guarantors', ['organisation_id'], unique=False)
    op.add_column('loan_collaterals', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('loan_collaterals_organisation_id_fkey'), 'loan_collaterals', 'organisations', ['organisation_id'], ['id'])
    op.create_index(op.f('ix_loan_collaterals_organisation_id'), 'loan_collaterals', ['organisation_id'], unique=False)
    op.add_column('loan_applications', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('loan_applications_organisation_id_fkey'), 'loan_applications', 'organisations', ['organisation_id'], ['id'])
    op.create_index(op.f('ix_loan_applications_organisation_id'), 'loan_applications', ['organisation_id'], unique=False)
    # ### end Alembic commands ###
