"""organisation removal

Revision ID: c6dc33f99d51
Revises: a50fdbd8eb69
Create Date: 2026-05-19 17:02:29.115268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6dc33f99d51'
down_revision: Union[str, Sequence[str], None] = 'a50fdbd8eb69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_savings_accounts_organisation_id'), table_name='savings_accounts')
    op.drop_constraint(op.f('savings_accounts_organisation_id_fkey'), 'savings_accounts', type_='foreignkey')
    op.drop_column('savings_accounts', 'organisation_id')
    op.drop_index(op.f('ix_savings_products_organisation_id'), table_name='savings_products')
    op.drop_constraint(op.f('savings_products_organisation_id_fkey'), 'savings_products', type_='foreignkey')
    op.drop_column('savings_products', 'organisation_id')
    op.drop_index(op.f('ix_savings_transactions_organisation_id'), table_name='savings_transactions')
    op.drop_constraint(op.f('savings_transactions_organisation_id_fkey'), 'savings_transactions', type_='foreignkey')
    op.drop_column('savings_transactions', 'organisation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings_transactions', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('savings_transactions_organisation_id_fkey'), 'savings_transactions', 'organisations', ['organisation_id'], ['id'])
    op.create_index(op.f('ix_savings_transactions_organisation_id'), 'savings_transactions', ['organisation_id'], unique=False)
    op.add_column('savings_products', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('savings_products_organisation_id_fkey'), 'savings_products', 'organisations', ['organisation_id'], ['id'])
    op.create_index(op.f('ix_savings_products_organisation_id'), 'savings_products', ['organisation_id'], unique=False)
    op.add_column('savings_accounts', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('savings_accounts_organisation_id_fkey'), 'savings_accounts', 'organisations', ['organisation_id'], ['id'])
    op.create_index(op.f('ix_savings_accounts_organisation_id'), 'savings_accounts', ['organisation_id'], unique=False)
    # ### end Alembic commands ###
