"""change

Revision ID: c9c4b13fc2a3
Revises: 5c99d740f48b
Create Date: 2026-05-17 23:36:22.120014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9c4b13fc2a3'
down_revision: Union[str, Sequence[str], None] = '5c99d740f48b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marital_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_type')
    )
    op.drop_table('transactions')
    op.drop_table('accounts')
    op.add_column('branches', sa.Column('branch_name', sa.String(length=255), nullable=False))
    op.add_column('branches', sa.Column('branch_phone', sa.String(length=30), nullable=True))
    op.add_column('branches', sa.Column('branch_email', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_column('branches', 'phone')
    op.drop_column('branches', 'name')
    op.drop_column('branches', 'email')
    op.add_column('genders', sa.Column('gender', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('genders_code_key'), 'genders', type_='unique')
    op.create_unique_constraint(None, 'genders', ['gender'])
    op.drop_column('genders', 'name')
    op.drop_column('genders', 'code')
    op.drop_constraint(op.f('login_logs_member_id_fkey'), 'login_logs', type_='foreignkey')
    op.create_foreign_key(None, 'login_logs', 'users', ['member_id'], ['id'], ondelete='CASCADE')
    op.add_column('member_statuses', sa.Column('status', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('member_statuses_code_key'), 'member_statuses', type_='unique')
    op.create_unique_constraint(None, 'member_statuses', ['status'])
    op.drop_column('member_statuses', 'name')
    op.drop_column('member_statuses', 'code')
    op.add_column('members', sa.Column('marital_status', sa.UUID(), nullable=True))
    op.add_column('members', sa.Column('phone', sa.String(length=30), nullable=True))
    op.alter_column('members', 'joined_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('members', 'exit_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_members_organisation_id'), table_name='members')
    op.drop_constraint(op.f('uq_member_no_per_org'), 'members', type_='unique')
    op.create_unique_constraint('uq_member_no_per_org', 'members', ['member_no'])
    op.create_unique_constraint(None, 'members', ['phone_primary'])
    op.create_unique_constraint(None, 'members', ['phone_secondary'])
    op.create_unique_constraint(None, 'members', ['phone'])
    op.drop_constraint(op.f('members_organisation_id_fkey'), 'members', type_='foreignkey')
    op.create_foreign_key(None, 'members', 'marital_status', ['marital_status'], ['id'], ondelete='CASCADE')
    op.drop_column('members', 'organisation_id')
    op.add_column('next_of_kin', sa.Column('member_relationship', sa.String(length=100), nullable=True))
    op.add_column('next_of_kin', sa.Column('marital_status', sa.UUID(), nullable=False))
    op.add_column('next_of_kin', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('next_of_kin', sa.Column('middle_name', sa.String(length=100), nullable=True))
    op.add_column('next_of_kin', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('next_of_kin', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'next_of_kin', ['phone'])
    op.create_foreign_key(None, 'next_of_kin', 'marital_status', ['marital_status'], ['id'], ondelete='CASCADE')
    op.drop_column('next_of_kin', 'full_name')
    op.drop_index(op.f('ix_organisations_id'), table_name='organisations')
    op.add_column('roles', sa.Column('role', sa.String(length=100), nullable=False))
    op.alter_column('roles', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)
    op.drop_constraint(op.f('roles_code_key'), 'roles', type_='unique')
    op.create_unique_constraint(None, 'roles', ['role'])
    op.drop_column('roles', 'name')
    op.drop_column('roles', 'code')
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('middle_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_users_organisation_id'), table_name='users')
    op.drop_constraint(op.f('users_member_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_user_email_per_org'), 'users', type_='unique')
    op.create_unique_constraint('uq_user_email_per_org', 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['phone'])
    op.drop_constraint(op.f('users_member_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_organisation_id_fkey'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'member_id')
    op.drop_column('users', 'organisation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('users_organisation_id_fkey'), 'users', 'organisations', ['organisation_id'], ['id'])
    op.create_foreign_key(op.f('users_member_id_fkey'), 'users', 'members', ['member_id'], ['id'])
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint('uq_user_email_per_org', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_user_email_per_org'), 'users', ['organisation_id', 'email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_member_id_key'), 'users', ['member_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_organisation_id'), 'users', ['organisation_id'], unique=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'first_name')
    op.add_column('roles', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_unique_constraint(op.f('roles_code_key'), 'roles', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('roles', 'description',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('roles', 'role')
    op.create_index(op.f('ix_organisations_id'), 'organisations', ['id'], unique=False)
    op.add_column('next_of_kin', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'next_of_kin', type_='foreignkey')
    op.drop_constraint(None, 'next_of_kin', type_='unique')
    op.drop_column('next_of_kin', 'email')
    op.drop_column('next_of_kin', 'last_name')
    op.drop_column('next_of_kin', 'middle_name')
    op.drop_column('next_of_kin', 'first_name')
    op.drop_column('next_of_kin', 'marital_status')
    op.drop_column('next_of_kin', 'member_relationship')
    op.add_column('members', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.create_foreign_key(op.f('members_organisation_id_fkey'), 'members', 'organisations', ['organisation_id'], ['id'])
    op.drop_constraint(None, 'members', type_='unique')
    op.drop_constraint(None, 'members', type_='unique')
    op.drop_constraint(None, 'members', type_='unique')
    op.drop_constraint('uq_member_no_per_org', 'members', type_='unique')
    op.create_unique_constraint(op.f('uq_member_no_per_org'), 'members', ['organisation_id', 'member_no'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_members_organisation_id'), 'members', ['organisation_id'], unique=False)
    op.alter_column('members', 'exit_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('members', 'joined_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('members', 'phone')
    op.drop_column('members', 'marital_status')
    op.add_column('member_statuses', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('member_statuses', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'member_statuses', type_='unique')
    op.create_unique_constraint(op.f('member_statuses_code_key'), 'member_statuses', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('member_statuses', 'status')
    op.drop_constraint(None, 'login_logs', type_='foreignkey')
    op.create_foreign_key(op.f('login_logs_member_id_fkey'), 'login_logs', 'users', ['member_id'], ['member_id'], ondelete='CASCADE')
    op.add_column('genders', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('genders', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'genders', type_='unique')
    op.create_unique_constraint(op.f('genders_code_key'), 'genders', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('genders', 'gender')
    op.add_column('branches', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('branches', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('branches', sa.Column('phone', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.drop_column('branches', 'branch_email')
    op.drop_column('branches', 'branch_phone')
    op.drop_column('branches', 'branch_name')
    op.create_table('accounts',
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_name', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('account_created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('account_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('account_id', name=op.f('accounts_pkey')),
    sa.UniqueConstraint('account_name', name=op.f('accounts_account_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('transactions',
    sa.Column('txn_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('transaction_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['users.member_id'], name=op.f('transactions_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('txn_id', name=op.f('transactions_pkey'))
    )
    op.drop_table('user_types')
    op.drop_table('marital_status')
    # ### end Alembic commands ###
