"""org

Revision ID: cc3b10151e6a
Revises: 9c2283c59cae
Create Date: 2026-05-22 13:21:48.532531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc3b10151e6a'
down_revision: Union[str, Sequence[str], None] = '9c2283c59cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_organisation_id'), table_name='members')
    op.drop_constraint(op.f('uq_member_no_per_org'), 'members', type_='unique')
    op.create_unique_constraint('uq_member_no_per_org', 'members', ['member_no'])
    op.drop_constraint(op.f('members_organisation_id_fkey'), 'members', type_='foreignkey')
    op.drop_column('members', 'organisation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('members_organisation_id_fkey'), 'members', 'organisations', ['organisation_id'], ['id'])
    op.drop_constraint('uq_member_no_per_org', 'members', type_='unique')
    op.create_unique_constraint(op.f('uq_member_no_per_org'), 'members', ['organisation_id', 'member_no'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_members_organisation_id'), 'members', ['organisation_id'], unique=False)
    # ### end Alembic commands ###
