"""changes

Revision ID: dea56b6a9172
Revises: b543dda4ef8a
Create Date: 2026-05-17 23:47:52.236967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea56b6a9172'
down_revision: Union[str, Sequence[str], None] = 'b543dda4ef8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'users', 'user_types', ['user_type'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###
