"""clear organisation

Revision ID: e4143df6215a
Revises: ba2002681fb8
Create Date: 2026-05-21 23:20:42.595986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4143df6215a'
down_revision: Union[str, Sequence[str], None] = 'ba2002681fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_users_organisation_id'), table_name='users')
    op.drop_constraint(op.f('uq_user_email_per_org'), 'users', type_='unique')
    op.create_unique_constraint('uq_user_email_per_org', 'users', ['email'])
    op.drop_constraint(op.f('users_organisation_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'organisation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organisation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_organisation_id_fkey'), 'users', 'organisations', ['organisation_id'], ['id'])
    op.drop_constraint('uq_user_email_per_org', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_user_email_per_org'), 'users', ['organisation_id', 'email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_organisation_id'), 'users', ['organisation_id'], unique=False)
    op.alter_column('users', 'role_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
