"""status

Revision ID: e5c1007aca25
Revises: 8d0956476591
Create Date: 2026-05-22 14:27:14.026291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c1007aca25'
down_revision: Union[str, Sequence[str], None] = '8d0956476591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'status_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'status_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
