"""initial db migration

Revision ID: e6440290a3f3
Revises:
Create Date: 2026-05-26 23:10:15.918548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e6440290a3f3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dividend_statuses",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", "id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_dividend_statuses_id"), "dividend_statuses", ["id"], unique=False
    )
    op.create_table(
        "genders",
        sa.Column("gender", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gender"),
    )
    op.create_index(op.f("ix_genders_id"), "genders", ["id"], unique=False)
    op.create_table(
        "ledger_account_categories",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", "id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_ledger_account_categories_id"),
        "ledger_account_categories",
        ["id"],
        unique=False,
    )
    op.create_table(
        "ledger_account_types",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", "id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_ledger_account_types_id"), "ledger_account_types", ["id"], unique=False
    )
    op.create_table(
        "ledger_dr_crs",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", "id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(op.f("ix_ledger_dr_crs_id"), "ledger_dr_crs", ["id"], unique=False)
    op.create_table(
        "ledger_entry_statuses",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", "id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_ledger_entry_statuses_id"),
        "ledger_entry_statuses",
        ["id"],
        unique=False,
    )
    op.create_table(
        "ledger_entry_types",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", "id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_ledger_entry_types_id"), "ledger_entry_types", ["id"], unique=False
    )
    op.create_table(
        "loan_application_statuses",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", "id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_loan_application_statuses_id"),
        "loan_application_statuses",
        ["id"],
        unique=False,
    )
    op.create_table(
        "loan_collateral_types",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", "id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_loan_collateral_types_id"),
        "loan_collateral_types",
        ["id"],
        unique=False,
    )
    op.create_table(
        "loan_interest_methods",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", "id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_loan_interest_methods_id"),
        "loan_interest_methods",
        ["id"],
        unique=False,
    )
    op.create_table(
        "loan_penalty_types",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", "id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_loan_penalty_types_id"), "loan_penalty_types", ["id"], unique=False
    )
    op.create_table(
        "loan_repayment_frequencies",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", "id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_loan_repayment_frequencies_id"),
        "loan_repayment_frequencies",
        ["id"],
        unique=False,
    )
    op.create_table(
        "loan_statuses",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", "id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(op.f("ix_loan_statuses_id"), "loan_statuses", ["id"], unique=False)
    op.create_table(
        "marital_statuses",
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("status"),
    )
    op.create_index(
        op.f("ix_marital_statuses_id"), "marital_statuses", ["id"], unique=False
    )
    op.create_table(
        "member_statuses",
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("status"),
    )
    op.create_index(
        op.f("ix_member_statuses_id"), "member_statuses", ["id"], unique=False
    )
    op.create_table(
        "organisations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("short_code", sa.String(length=20), nullable=False),
        sa.Column("registration_no", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("logo_url", sa.String(length=512), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("default_currency", sa.String(length=10), nullable=False),
        sa.Column("min_share_value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "loan_interest_rate", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "savings_interest_rate", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("short_code"),
    )
    op.create_table(
        "roles",
        sa.Column("role", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=250), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_table(
        "savings_account_statuses",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_savings_account_statuses_code"),
        "savings_account_statuses",
        ["code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_savings_account_statuses_id"),
        "savings_account_statuses",
        ["id"],
        unique=False,
    )
    op.create_table(
        "savings_product_types",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_savings_product_types_code"),
        "savings_product_types",
        ["code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_savings_product_types_id"),
        "savings_product_types",
        ["id"],
        unique=False,
    )
    op.create_table(
        "savings_tx_types",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_savings_tx_types_code"), "savings_tx_types", ["code"], unique=True
    )
    op.create_index(
        op.f("ix_savings_tx_types_id"), "savings_tx_types", ["id"], unique=False
    )
    op.create_table(
        "share_product_types",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", "id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_share_product_types_id"), "share_product_types", ["id"], unique=False
    )
    op.create_table(
        "share_transaction_types",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", "id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_share_transaction_types_id"),
        "share_transaction_types",
        ["id"],
        unique=False,
    )
    op.create_table(
        "user_types",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", "id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(op.f("ix_user_types_id"), "user_types", ["id"], unique=False)
    op.create_table(
        "branches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column("branch_name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("manager_name", sa.String(length=255), nullable=True),
        sa.Column("branch_phone", sa.String(length=30), nullable=True),
        sa.Column("branch_email", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_branches_organisation_id"),
        "branches",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "chart_of_accounts",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("account_type", sa.String(length=50), nullable=False),
        sa.Column("account_category", sa.String(length=50), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_category"],
            ["ledger_account_categories.code"],
        ),
        sa.ForeignKeyConstraint(
            ["account_type"],
            ["ledger_account_types.code"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["chart_of_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_chart_of_accounts_id"), "chart_of_accounts", ["id"], unique=False
    )
    op.create_table(
        "loan_products",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("interest_rate_pa", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("interest_method", sa.String(length=50), nullable=False),
        sa.Column("repayment_frequency", sa.String(length=50), nullable=False),
        sa.Column("min_term_months", sa.Integer(), nullable=False),
        sa.Column("max_term_months", sa.Integer(), nullable=False),
        sa.Column("min_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("max_amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column(
            "loan_to_savings_ratio", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column(
            "loan_to_shares_ratio", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("requires_guarantor", sa.Boolean(), nullable=False),
        sa.Column("min_guarantors", sa.Integer(), nullable=False),
        sa.Column("requires_collateral", sa.Boolean(), nullable=False),
        sa.Column(
            "penalty_rate_per_day", sa.Numeric(precision=5, scale=4), nullable=False
        ),
        sa.Column(
            "processing_fee_pct", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("loan_receivable_account_id", sa.UUID(), nullable=True),
        sa.Column("interest_income_account_id", sa.UUID(), nullable=True),
        sa.Column("penalty_income_account_id", sa.UUID(), nullable=True),
        sa.Column("processing_fee_account_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["interest_income_account_id"],
            ["chart_of_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["interest_method"],
            ["loan_interest_methods.code"],
        ),
        sa.ForeignKeyConstraint(
            ["loan_receivable_account_id"],
            ["chart_of_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["penalty_income_account_id"],
            ["chart_of_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["processing_fee_account_id"],
            ["chart_of_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repayment_frequency"],
            ["loan_repayment_frequencies.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(op.f("ix_loan_products_id"), "loan_products", ["id"], unique=False)
    op.create_table(
        "members",
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("gender_id", sa.UUID(), nullable=False),
        sa.Column("status_id", sa.UUID(), nullable=True),
        sa.Column("marital_status_id", sa.UUID(), nullable=True),
        sa.Column("member_no", sa.String(length=50), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("national_id", sa.String(length=50), nullable=False),
        sa.Column("photo_url", sa.String(length=512), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone_primary", sa.String(length=30), nullable=True),
        sa.Column("phone_secondary", sa.String(length=30), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("village", sa.String(length=255), nullable=True),
        sa.Column("district", sa.String(length=255), nullable=True),
        sa.Column("physical_address", sa.Text(), nullable=True),
        sa.Column("joined_date", sa.Date(), nullable=True),
        sa.Column("exit_date", sa.Date(), nullable=True),
        sa.Column("exit_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gender_id"],
            ["genders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["marital_status_id"],
            ["marital_statuses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["member_statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_no", name="uq_member_no_per_org"),
        sa.UniqueConstraint("phone_primary"),
    )
    op.create_index(
        op.f("ix_members_branch_id"), "members", ["branch_id"], unique=False
    )
    op.create_index(op.f("ix_members_id"), "members", ["id"], unique=False)
    op.create_index(op.f("ix_members_member_no"), "members", ["member_no"], unique=True)
    op.create_table(
        "payment_channel_configurations",
        sa.Column("channel_code", sa.String(length=50), nullable=False),
        sa.Column("channel_name", sa.String(length=100), nullable=False),
        sa.Column("asset_account_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_account_id"],
            ["chart_of_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("channel_code", "id"),
    )
    op.create_index(
        op.f("ix_payment_channel_configurations_channel_code"),
        "payment_channel_configurations",
        ["channel_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_payment_channel_configurations_id"),
        "payment_channel_configurations",
        ["id"],
        unique=False,
    )
    op.create_table(
        "savings_products",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("product_type", sa.String(length=50), nullable=False),
        sa.Column("product_type_id", sa.UUID(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("interest_rate_pa", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "min_opening_balance", sa.Numeric(precision=18, scale=4), nullable=False
        ),
        sa.Column("min_balance", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("max_balance", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("withdrawal_allowed", sa.Boolean(), nullable=False),
        sa.Column("lock_period_days", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("savings_control_account_id", sa.UUID(), nullable=False),
        sa.Column("interest_expense_account_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["interest_expense_account_id"],
            ["chart_of_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_type_id"],
            ["savings_product_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["savings_control_account_id"],
            ["chart_of_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_savings_products_id"), "savings_products", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_savings_products_product_type_id"),
        "savings_products",
        ["product_type_id"],
        unique=False,
    )
    op.create_table(
        "share_products",
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("product_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("nominal_value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("min_shares", sa.Integer(), nullable=False),
        sa.Column("max_shares", sa.Integer(), nullable=True),
        sa.Column("is_transferable", sa.Boolean(), nullable=False),
        sa.Column("is_redeemable", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("share_capital_account_id", sa.UUID(), nullable=True),
        sa.Column("dividend_expense_account_id", sa.UUID(), nullable=True),
        sa.Column("dividend_payable_account_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dividend_expense_account_id"],
            ["chart_of_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dividend_payable_account_id"],
            ["chart_of_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_type"],
            ["share_product_types.code"],
        ),
        sa.ForeignKeyConstraint(
            ["share_capital_account_id"],
            ["chart_of_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_share_products_id"), "share_products", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_share_products_organisation_id"),
        "share_products",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "next_of_kin",
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("marital_status_id", sa.UUID(), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("national_id", sa.String(length=50), nullable=True),
        sa.Column("relationship_to_member", sa.String(length=100), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["marital_status_id"],
            ["marital_statuses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_next_of_kin_id"), "next_of_kin", ["id"], unique=False)
    op.create_index(
        op.f("ix_next_of_kin_member_id"), "next_of_kin", ["member_id"], unique=False
    )
    op.create_table(
        "savings_accounts",
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("account_no", sa.String(length=50), nullable=False),
        sa.Column("balance", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("status_id", sa.UUID(), nullable=True),
        sa.Column("opened_date", sa.Date(), nullable=True),
        sa.Column("closed_date", sa.Date(), nullable=True),
        sa.Column("maturity_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["savings_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["savings_account_statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_savings_accounts_branch_id"),
        "savings_accounts",
        ["branch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_savings_accounts_id"), "savings_accounts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_savings_accounts_member_id"),
        "savings_accounts",
        ["member_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_savings_accounts_status_id"),
        "savings_accounts",
        ["status_id"],
        unique=False,
    )
    op.create_table(
        "share_accounts",
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("account_no", sa.String(length=50), nullable=False),
        sa.Column("shares_held", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["share_products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_share_accounts_branch_id"),
        "share_accounts",
        ["branch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_share_accounts_id"), "share_accounts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_share_accounts_member_id"),
        "share_accounts",
        ["member_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_share_accounts_organisation_id"),
        "share_accounts",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("role_name", sa.String(length=15), nullable=True),
        sa.Column("user_type", sa.String(length=50), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["member_id"], ["members.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_name"], ["roles.role"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["user_type"],
            ["user_types.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_user_email_per_org"),
        sa.UniqueConstraint("member_id"),
        sa.UniqueConstraint("role_name"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "dividends",
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("period_label", sa.String(length=50), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("rate_percent", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("approved_by_id", sa.UUID(), nullable=True),
        sa.Column("approved_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["share_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status"],
            ["dividend_statuses.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dividends_id"), "dividends", ["id"], unique=False)
    op.create_index(
        op.f("ix_dividends_organisation_id"),
        "dividends",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "ledger_entries",
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("entry_no", sa.String(length=50), nullable=False),
        sa.Column("entry_type", sa.String(length=50), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("total_debit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_credit", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("reversal_of_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.CheckConstraint("total_debit = total_credit", name="ck_ledger_balanced"),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entry_type"],
            ["ledger_entry_types.code"],
        ),
        sa.ForeignKeyConstraint(
            ["reversal_of_id"],
            ["ledger_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status"],
            ["ledger_entry_statuses.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ledger_entries_branch_id"),
        "ledger_entries",
        ["branch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ledger_entries_id"), "ledger_entries", ["id"], unique=False
    )
    op.create_table(
        "loan_applications",
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("application_no", sa.String(length=50), nullable=False),
        sa.Column("applied_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("approved_amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("term_months", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("applied_date", sa.Date(), nullable=False),
        sa.Column("reviewed_date", sa.Date(), nullable=True),
        sa.Column("decision_date", sa.Date(), nullable=True),
        sa.Column("reviewed_by_id", sa.UUID(), nullable=True),
        sa.Column("decision_by_id", sa.UUID(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["decision_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["loan_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status"],
            ["loan_application_statuses.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_loan_applications_branch_id"),
        "loan_applications",
        ["branch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_loan_applications_id"), "loan_applications", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_loan_applications_member_id"),
        "loan_applications",
        ["member_id"],
        unique=False,
    )
    op.create_table(
        "login_logs",
        sa.Column("log_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "login_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ip_address", sa.String(length=30), nullable=True),
        sa.Column("user_agent", sa.String(length=250), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("failure_reason", sa.String(length=30), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="1", nullable=False),
        sa.Column("session_id", sa.String(length=30), nullable=True),
        sa.Column("location_country", sa.String(length=50), nullable=True),
        sa.Column("location_city", sa.String(length=50), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("log_id", "id"),
    )
    op.create_index(op.f("ix_login_logs_id"), "login_logs", ["id"], unique=False)
    op.create_table(
        "mobile_money_transactions",
        sa.Column("phone_number", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("transaction_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=False),
        sa.Column("transaction_id", sa.String(length=100), nullable=True),
        sa.Column("provider_response", sa.Text(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mobile_money_transactions_id"),
        "mobile_money_transactions",
        ["id"],
        unique=False,
    )
    op.create_table(
        "dividend_payments",
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column("dividend_id", sa.UUID(), nullable=False),
        sa.Column("share_account_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column(
            "shares_at_record", sa.Numeric(precision=18, scale=4), nullable=False
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("paid_date", sa.Date(), nullable=True),
        sa.Column("payment_method", sa.String(length=50), nullable=True),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("ledger_entry_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dividend_id"],
            ["dividends.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ledger_entry_id"],
            ["ledger_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["share_account_id"],
            ["share_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dividend_payments_dividend_id"),
        "dividend_payments",
        ["dividend_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dividend_payments_id"), "dividend_payments", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_dividend_payments_organisation_id"),
        "dividend_payments",
        ["organisation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dividend_payments_share_account_id"),
        "dividend_payments",
        ["share_account_id"],
        unique=False,
    )
    op.create_table(
        "journal_entries",
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("ledger_entry_id", sa.UUID(), nullable=False),
        sa.Column("narration", sa.Text(), nullable=False),
        sa.Column("prepared_by_id", sa.UUID(), nullable=False),
        sa.Column("approved_by_id", sa.UUID(), nullable=True),
        sa.Column("approved_date", sa.Date(), nullable=True),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ledger_entry_id"],
            ["ledger_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["prepared_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ledger_entry_id"),
    )
    op.create_index(
        op.f("ix_journal_entries_branch_id"),
        "journal_entries",
        ["branch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_journal_entries_id"), "journal_entries", ["id"], unique=False
    )
    op.create_table(
        "ledger_lines",
        sa.Column("entry_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("dr_cr", sa.String(length=50), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("member_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.CheckConstraint("amount > 0", name="ck_ledger_line_positive"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["chart_of_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["dr_cr"],
            ["ledger_dr_crs.code"],
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["ledger_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ledger_lines_account_id"), "ledger_lines", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_ledger_lines_entry_id"), "ledger_lines", ["entry_id"], unique=False
    )
    op.create_index(op.f("ix_ledger_lines_id"), "ledger_lines", ["id"], unique=False)
    op.create_table(
        "loan_collaterals",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("collateral_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("estimated_value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("document_ref", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["loan_applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["collateral_type"],
            ["loan_collateral_types.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_loan_collaterals_application_id"),
        "loan_collaterals",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_loan_collaterals_id"), "loan_collaterals", ["id"], unique=False
    )
    op.create_table(
        "loan_guarantors",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("guarantor_id", sa.UUID(), nullable=False),
        sa.Column(
            "guaranteed_amount", sa.Numeric(precision=18, scale=4), nullable=True
        ),
        sa.Column("has_consented", sa.Boolean(), nullable=False),
        sa.Column("consent_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["loan_applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["guarantor_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_loan_guarantors_application_id"),
        "loan_guarantors",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_loan_guarantors_id"), "loan_guarantors", ["id"], unique=False
    )
    op.create_table(
        "loans",
        sa.Column("branch_id", sa.UUID(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("loan_no", sa.String(length=50), nullable=False),
        sa.Column("principal", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("interest_rate_pa", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("term_months", sa.Integer(), nullable=False),
        sa.Column("interest_method", sa.String(length=50), nullable=False),
        sa.Column("repayment_frequency", sa.String(length=50), nullable=False),
        sa.Column("processing_fee", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_interest", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_payable", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "outstanding_principal", sa.Numeric(precision=18, scale=4), nullable=False
        ),
        sa.Column(
            "outstanding_interest", sa.Numeric(precision=18, scale=4), nullable=False
        ),
        sa.Column(
            "outstanding_penalty", sa.Numeric(precision=18, scale=4), nullable=False
        ),
        sa.Column("total_paid", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("disbursement_date", sa.Date(), nullable=False),
        sa.Column("first_payment_date", sa.Date(), nullable=False),
        sa.Column("maturity_date", sa.Date(), nullable=False),
        sa.Column("closed_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("disbursed_by_id", sa.UUID(), nullable=True),
        sa.Column("ledger_entry_id", sa.UUID(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["loan_applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["disbursed_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["interest_method"],
            ["loan_interest_methods.code"],
        ),
        sa.ForeignKeyConstraint(
            ["ledger_entry_id"],
            ["ledger_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["loan_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repayment_frequency"],
            ["loan_repayment_frequencies.code"],
        ),
        sa.ForeignKeyConstraint(
            ["status"],
            ["loan_statuses.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("application_id"),
    )
    op.create_index(op.f("ix_loans_branch_id"), "loans", ["branch_id"], unique=False)
    op.create_index(op.f("ix_loans_id"), "loans", ["id"], unique=False)
    op.create_index(op.f("ix_loans_member_id"), "loans", ["member_id"], unique=False)
    op.create_table(
        "savings_transactions",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("ledger_entry_id", sa.UUID(), nullable=True),
        sa.Column("tx_type_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("processed_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["savings_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ledger_entry_id"],
            ["ledger_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["processed_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tx_type_id"],
            ["savings_tx_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_savings_transactions_account_id"),
        "savings_transactions",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_savings_transactions_id"), "savings_transactions", ["id"], unique=False
    )
    op.create_table(
        "share_transactions",
        sa.Column("organisation_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("ledger_entry_id", sa.UUID(), nullable=True),
        sa.Column("tx_type", sa.String(length=50), nullable=False),
        sa.Column("shares", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("price_per_share", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("shares_after", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("processed_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["share_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ledger_entry_id"],
            ["ledger_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["processed_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tx_type"],
            ["share_transaction_types.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_share_transactions_account_id"),
        "share_transactions",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_share_transactions_id"), "share_transactions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_share_transactions_organisation_id"),
        "share_transactions",
        ["organisation_id"],
        unique=False,
    )
    op.create_table(
        "loan_penalties",
        sa.Column("loan_id", sa.UUID(), nullable=False),
        sa.Column("penalty_type", sa.String(length=50), nullable=False),
        sa.Column("days_overdue", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("amount_paid", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("is_waived", sa.Boolean(), nullable=False),
        sa.Column("waived_by_id", sa.UUID(), nullable=True),
        sa.Column("raised_date", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["loan_id"],
            ["loans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["penalty_type"],
            ["loan_penalty_types.code"],
        ),
        sa.ForeignKeyConstraint(
            ["waived_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_loan_penalties_id"), "loan_penalties", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_loan_penalties_loan_id"), "loan_penalties", ["loan_id"], unique=False
    )
    op.create_table(
        "loan_repayment_schedules",
        sa.Column("loan_id", sa.UUID(), nullable=False),
        sa.Column("instalment_no", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("principal_due", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("interest_due", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("total_due", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("principal_paid", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("interest_paid", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("penalty_paid", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("is_paid", sa.Boolean(), nullable=False),
        sa.Column("paid_date", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["loan_id"],
            ["loans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_loan_repayment_schedules_id"),
        "loan_repayment_schedules",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_loan_repayment_schedules_loan_id"),
        "loan_repayment_schedules",
        ["loan_id"],
        unique=False,
    )
    op.create_table(
        "loan_repayments",
        sa.Column("loan_id", sa.UUID(), nullable=False),
        sa.Column("ledger_entry_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "principal_portion", sa.Numeric(precision=18, scale=4), nullable=False
        ),
        sa.Column(
            "interest_portion", sa.Numeric(precision=18, scale=4), nullable=False
        ),
        sa.Column("penalty_portion", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("payment_method", sa.String(length=50), nullable=True),
        sa.Column("reference", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("received_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ledger_entry_id"],
            ["ledger_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["loan_id"],
            ["loans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["received_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_loan_repayments_id"), "loan_repayments", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_loan_repayments_loan_id"), "loan_repayments", ["loan_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_loan_repayments_loan_id"), table_name="loan_repayments")
    op.drop_index(op.f("ix_loan_repayments_id"), table_name="loan_repayments")
    op.drop_table("loan_repayments")
    op.drop_index(
        op.f("ix_loan_repayment_schedules_loan_id"),
        table_name="loan_repayment_schedules",
    )
    op.drop_index(
        op.f("ix_loan_repayment_schedules_id"), table_name="loan_repayment_schedules"
    )
    op.drop_table("loan_repayment_schedules")
    op.drop_index(op.f("ix_loan_penalties_loan_id"), table_name="loan_penalties")
    op.drop_index(op.f("ix_loan_penalties_id"), table_name="loan_penalties")
    op.drop_table("loan_penalties")
    op.drop_index(
        op.f("ix_share_transactions_organisation_id"), table_name="share_transactions"
    )
    op.drop_index(op.f("ix_share_transactions_id"), table_name="share_transactions")
    op.drop_index(
        op.f("ix_share_transactions_account_id"), table_name="share_transactions"
    )
    op.drop_table("share_transactions")
    op.drop_index(op.f("ix_savings_transactions_id"), table_name="savings_transactions")
    op.drop_index(
        op.f("ix_savings_transactions_account_id"), table_name="savings_transactions"
    )
    op.drop_table("savings_transactions")
    op.drop_index(op.f("ix_loans_member_id"), table_name="loans")
    op.drop_index(op.f("ix_loans_id"), table_name="loans")
    op.drop_index(op.f("ix_loans_branch_id"), table_name="loans")
    op.drop_table("loans")
    op.drop_index(op.f("ix_loan_guarantors_id"), table_name="loan_guarantors")
    op.drop_index(
        op.f("ix_loan_guarantors_application_id"), table_name="loan_guarantors"
    )
    op.drop_table("loan_guarantors")
    op.drop_index(op.f("ix_loan_collaterals_id"), table_name="loan_collaterals")
    op.drop_index(
        op.f("ix_loan_collaterals_application_id"), table_name="loan_collaterals"
    )
    op.drop_table("loan_collaterals")
    op.drop_index(op.f("ix_ledger_lines_id"), table_name="ledger_lines")
    op.drop_index(op.f("ix_ledger_lines_entry_id"), table_name="ledger_lines")
    op.drop_index(op.f("ix_ledger_lines_account_id"), table_name="ledger_lines")
    op.drop_table("ledger_lines")
    op.drop_index(op.f("ix_journal_entries_id"), table_name="journal_entries")
    op.drop_index(op.f("ix_journal_entries_branch_id"), table_name="journal_entries")
    op.drop_table("journal_entries")
    op.drop_index(
        op.f("ix_dividend_payments_share_account_id"), table_name="dividend_payments"
    )
    op.drop_index(
        op.f("ix_dividend_payments_organisation_id"), table_name="dividend_payments"
    )
    op.drop_index(op.f("ix_dividend_payments_id"), table_name="dividend_payments")
    op.drop_index(
        op.f("ix_dividend_payments_dividend_id"), table_name="dividend_payments"
    )
    op.drop_table("dividend_payments")
    op.drop_index(
        op.f("ix_mobile_money_transactions_id"), table_name="mobile_money_transactions"
    )
    op.drop_table("mobile_money_transactions")
    op.drop_index(op.f("ix_login_logs_id"), table_name="login_logs")
    op.drop_table("login_logs")
    op.drop_index(
        op.f("ix_loan_applications_member_id"), table_name="loan_applications"
    )
    op.drop_index(op.f("ix_loan_applications_id"), table_name="loan_applications")
    op.drop_index(
        op.f("ix_loan_applications_branch_id"), table_name="loan_applications"
    )
    op.drop_table("loan_applications")
    op.drop_index(op.f("ix_ledger_entries_id"), table_name="ledger_entries")
    op.drop_index(op.f("ix_ledger_entries_branch_id"), table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_index(op.f("ix_dividends_organisation_id"), table_name="dividends")
    op.drop_index(op.f("ix_dividends_id"), table_name="dividends")
    op.drop_table("dividends")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_share_accounts_organisation_id"), table_name="share_accounts"
    )
    op.drop_index(op.f("ix_share_accounts_member_id"), table_name="share_accounts")
    op.drop_index(op.f("ix_share_accounts_id"), table_name="share_accounts")
    op.drop_index(op.f("ix_share_accounts_branch_id"), table_name="share_accounts")
    op.drop_table("share_accounts")
    op.drop_index(op.f("ix_savings_accounts_status_id"), table_name="savings_accounts")
    op.drop_index(op.f("ix_savings_accounts_member_id"), table_name="savings_accounts")
    op.drop_index(op.f("ix_savings_accounts_id"), table_name="savings_accounts")
    op.drop_index(op.f("ix_savings_accounts_branch_id"), table_name="savings_accounts")
    op.drop_table("savings_accounts")
    op.drop_index(op.f("ix_next_of_kin_member_id"), table_name="next_of_kin")
    op.drop_index(op.f("ix_next_of_kin_id"), table_name="next_of_kin")
    op.drop_table("next_of_kin")
    op.drop_index(
        op.f("ix_share_products_organisation_id"), table_name="share_products"
    )
    op.drop_index(op.f("ix_share_products_id"), table_name="share_products")
    op.drop_table("share_products")
    op.drop_index(
        op.f("ix_savings_products_product_type_id"), table_name="savings_products"
    )
    op.drop_index(op.f("ix_savings_products_id"), table_name="savings_products")
    op.drop_table("savings_products")
    op.drop_index(
        op.f("ix_payment_channel_configurations_id"),
        table_name="payment_channel_configurations",
    )
    op.drop_index(
        op.f("ix_payment_channel_configurations_channel_code"),
        table_name="payment_channel_configurations",
    )
    op.drop_table("payment_channel_configurations")
    op.drop_index(op.f("ix_members_member_no"), table_name="members")
    op.drop_index(op.f("ix_members_id"), table_name="members")
    op.drop_index(op.f("ix_members_branch_id"), table_name="members")
    op.drop_table("members")
    op.drop_index(op.f("ix_loan_products_id"), table_name="loan_products")
    op.drop_table("loan_products")
    op.drop_index(op.f("ix_chart_of_accounts_id"), table_name="chart_of_accounts")
    op.drop_table("chart_of_accounts")
    op.drop_index(op.f("ix_branches_organisation_id"), table_name="branches")
    op.drop_table("branches")
    op.drop_index(op.f("ix_user_types_id"), table_name="user_types")
    op.drop_table("user_types")
    op.drop_index(
        op.f("ix_share_transaction_types_id"), table_name="share_transaction_types"
    )
    op.drop_table("share_transaction_types")
    op.drop_index(op.f("ix_share_product_types_id"), table_name="share_product_types")
    op.drop_table("share_product_types")
    op.drop_index(op.f("ix_savings_tx_types_id"), table_name="savings_tx_types")
    op.drop_index(op.f("ix_savings_tx_types_code"), table_name="savings_tx_types")
    op.drop_table("savings_tx_types")
    op.drop_index(
        op.f("ix_savings_product_types_id"), table_name="savings_product_types"
    )
    op.drop_index(
        op.f("ix_savings_product_types_code"), table_name="savings_product_types"
    )
    op.drop_table("savings_product_types")
    op.drop_index(
        op.f("ix_savings_account_statuses_id"), table_name="savings_account_statuses"
    )
    op.drop_index(
        op.f("ix_savings_account_statuses_code"), table_name="savings_account_statuses"
    )
    op.drop_table("savings_account_statuses")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_table("organisations")
    op.drop_index(op.f("ix_member_statuses_id"), table_name="member_statuses")
    op.drop_table("member_statuses")
    op.drop_index(op.f("ix_marital_statuses_id"), table_name="marital_statuses")
    op.drop_table("marital_statuses")
    op.drop_index(op.f("ix_loan_statuses_id"), table_name="loan_statuses")
    op.drop_table("loan_statuses")
    op.drop_index(
        op.f("ix_loan_repayment_frequencies_id"),
        table_name="loan_repayment_frequencies",
    )
    op.drop_table("loan_repayment_frequencies")
    op.drop_index(op.f("ix_loan_penalty_types_id"), table_name="loan_penalty_types")
    op.drop_table("loan_penalty_types")
    op.drop_index(
        op.f("ix_loan_interest_methods_id"), table_name="loan_interest_methods"
    )
    op.drop_table("loan_interest_methods")
    op.drop_index(
        op.f("ix_loan_collateral_types_id"), table_name="loan_collateral_types"
    )
    op.drop_table("loan_collateral_types")
    op.drop_index(
        op.f("ix_loan_application_statuses_id"), table_name="loan_application_statuses"
    )
    op.drop_table("loan_application_statuses")
    op.drop_index(op.f("ix_ledger_entry_types_id"), table_name="ledger_entry_types")
    op.drop_table("ledger_entry_types")
    op.drop_index(
        op.f("ix_ledger_entry_statuses_id"), table_name="ledger_entry_statuses"
    )
    op.drop_table("ledger_entry_statuses")
    op.drop_index(op.f("ix_ledger_dr_crs_id"), table_name="ledger_dr_crs")
    op.drop_table("ledger_dr_crs")
    op.drop_index(op.f("ix_ledger_account_types_id"), table_name="ledger_account_types")
    op.drop_table("ledger_account_types")
    op.drop_index(
        op.f("ix_ledger_account_categories_id"), table_name="ledger_account_categories"
    )
    op.drop_table("ledger_account_categories")
    op.drop_index(op.f("ix_genders_id"), table_name="genders")
    op.drop_table("genders")
    op.drop_index(op.f("ix_dividend_statuses_id"), table_name="dividend_statuses")
    op.drop_table("dividend_statuses")
    # ### end Alembic commands ###
