"""chang

Revision ID: f897cd98c877
Revises: 228ae6ca9eb6
Create Date: 2026-05-17 23:53:45.059383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f897cd98c877'
down_revision: Union[str, Sequence[str], None] = '228ae6ca9eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_column('members', 'user_id')
    # ### end Alembic commands ###
